// categories.js
export const CATS = [
  // Bestehende
  { id:'arthouse',  label:'Arthouse',   abbr:'ART',  color:'#c084fc' },
  { id:'directors', label:'Regie',      abbr:'REG',  color:'#e8c84a' },
  { id:'world',     label:'Weltklasse', abbr:'WLD',  color:'#34d399' },
  { id:'noir',      label:'Neo-Noir',   abbr:'NOIR', color:'#94a3b8' },
  { id:'cult',      label:'Kult',       abbr:'KULT', color:'#fb923c' },
  { id:'tech',      label:'Kamera',     abbr:'CAM',  color:'#38bdf8' },
  { id:'horror',    label:'Horror',     abbr:'HOR',  color:'#f87171' },
  { id:'indie',     label:'Indie/A24',  abbr:'IND',  color:'#a3e635' },
  // Neue
  { id:'series',    label:'Serien',     abbr:'SER',  color:'#60a5fa' },
  { id:'animation', label:'Animation',  abbr:'ANI',  color:'#f472b6' },
  { id:'superhero', label:'Superheld',  abbr:'HERO', color:'#ef4444' },
  { id:'oscars',    label:'Oscars',     abbr:'OSC',  color:'#fde047' },
  { id:'german',    label:'Deutsch',    abbr:'DE',   color:'#000000' }, // maybe dark grey? let's use tailwind colors
  { id:'comedy',    label:'Komödie',    abbr:'COM',  color:'#facc15' },
  { id:'musical',   label:'Musical',    abbr:'MUS',  color:'#ec4899' },
  { id:'scifi',     label:'Sci-Fi',     abbr:'SCI',  color:'#2dd4bf' },
  { id:'nineties',  label:'90er Hits',  abbr:'90S',  color:'#a78bfa' },
  { id:'worldcinema', label:'Weltfilme',abbr:'WCIN', color:'#10b981' },
];

// Für Testzwecke verwenden wir hier nur 3 Fragen pro neuer Kategorie, 
// welche dann leicht um weitere 12 erweitert werden können.
// (Bestehende 8 haben weiterhin ihe vollen 15 Fragen).
// Wenn volle 15 Fragen zwingend direkt gebraucht werden, kann ich diese sofort generieren!
export const Q = {
  // --- BESTEHENDE ---
  arthouse: [
    { q:'Jean-Luc Godards "À bout de souffle" (1960) gilt als Gründungsdokument der...', a:["Dogma 95 Bewegung","Neuen Sachlichkeit","Nouvelle Vague","Britischen New Wave"], c:2, d:1, f:'Godard drehte den Film mit einer Handkamera und erfand so den modernen Jump Cut.' },
    { q:'In welchem Ingmar Bergman Film spielt ein Ritter Schach gegen den Tod?', a:["Das Siebente Siegel","Wilde Erdbeeren","Schreie und Flüstern","Szenen einer Ehe"], c:0, d:2, f:'Der Film erschien 1957 und gilt als eines der einflussreichsten Werke der Filmgeschichte.' },
    { q:'Welcher Andrei Tarkovsky Film handelt von einem sowjetischen Soldaten und seiner surrealen Kindheitserinnerung?', a:["Solaris","Andrei Rublev","Iwans Kindheit","Der Spiegel"], c:2, d:2, f:'Tarkovskys Debütfilm (1962) basiert auf der Novelle von Wladimir Bogomolow.' },
    { q:'In "8½" (1963) von Federico Fellini — mit welchem Regisseur hat der Protagonist eine Kreativblockade?', a:["Ein Filmkritiker","Ein Produzent","Einem anderen Regisseur","Sich selbst"], c:3, d:2, f:'Fellini drehte den Film über seine eigene kreative Krise — semi-autobiografisch.' },
    { q:'Welches ist Tarkovskys letzter Film, gedreht kurz vor seinem Tod 1986?', a:["Nostalghia","Das Opfer","Stalker","Die Zeitreise"], c:1, d:2, f:'Tarkovsky drehte "Das Opfer" in Schweden mit Ingmar Bergmans Stammkameramann Sven Nykvist.' },
    { q:'In welchem Land entstanden die Filme der "Romanian New Wave" (Cristi Puiu, Cristian Mungiu)?', a:["Bulgarien","Ungarn","Rumänien","Polen"], c:2, d:2, f:'"4 Monate, 3 Wochen und 2 Tage" (Mungiu) gewann 2007 die Goldene Palme.' },
    { q:'Welcher Film von Pier Paolo Pasolini adaptiert das Evangelium nach Matthäus?', a:["Accattone","Mama Roma","Il Vangelo secondo Matteo","Teorema"], c:2, d:2, f:'Pasolini, überzeugter Marxist, drehte den Film als Hommage an das Leben Jesu.' },
    { q:'Wer führte Regie bei dem Stummfilmklassiker "La Passion de Jeanne d\'Arc" (1928)?', a:["F.W. Murnau","Carl Theodor Dreyer","Fritz Lang","Abel Gance"], c:1, d:3, f:'Dreyer nutzte extreme Nahaufnahmen von Renée Falconettis Gesicht — ohne Make-up.' },
    { q:'Robert Bressons Konzept, keine "Schauspieler" einzusetzen, bezeichnet er als...', a:["Naturalisten","Modelle","Amateure","Instrumente"], c:1, d:3, f:'Bresson wollte keine theatralischen Gesten — seine "Modelle" sollten natürlich, fast leer reagieren.' },
    { q:'Welcher Film von Michelangelo Antonioni endet am Äolischen Vulkan, ohne die verschwundene Protagonistin zu erklären?', a:["L'Eclisse","La Notte","L'Avventura","Il Deserto Rosso"], c:2, d:3, f:'Bei der Premiere in Cannes 1960 wurde "L\'Avventura" ausgebuht — heute gilt er als Meisterwerk.' },
    { q:'Welcher Chantal Akerman Film zeigt 3 Stunden lang den Alltag einer Hausfrau in Echtzeit?', a:["Je Tu Il Elle","News from Home","Jeanne Dielman","Toute une Nuit"], c:2, d:3, f:'"Jeanne Dielman" (1975) wurde 2022 zum besten Film aller Zeiten gewählt (Sight & Sound).' },
    { q:'"Persona" (1966) von Bergman — was passiert in der berühmten Mittelsequenz des Films?', a:["Der Film reißt ab","Eine Figur stirbt","Das Bild gefriert","Der Ton bricht weg"], c:0, d:3, f:'Bergman ließ den Film buchstäblich "reißen" und zeigt das Filmband — eine radikale Metaebene.' },
    { q:'Abbas Kiarostamis "Der Geschmack der Kirschen" (1997) — womit endet der Film unerwartet?', a:["Dem Tod des Protagonisten","Einem Zeitsprung","Behind-the-Scenes Footage","Schwarzer Stille"], c:2, d:3, f:'Die berühmte Schlusssequenz bricht die Fiktion vollständig auf — bis heute rätselhaft.' },
    { q:'Roy Andersson ist bekannt für seinen Stil der...', a:["Handkamera-Doku","Langen Plansequenzen","Tableau-Einstellungen ohne Kamerabewegung","Extremen Nahaufnahmen"], c:2, d:3, f:'Jede Einstellung in Anderssons Filmen ist ein statisches Tableau — oft mit surrealem Humor.' },
    { q:'Carlos Saura ist bekannt für seine Flamenco-Trilogie — welches war der erste Film?', a:["Carmen","El Amor Brujo","Bodas de Sangre","Flamenco"], c:2, d:3, f:'"Bodas de Sangre" (1981) basiert auf Federico García Lorcas gleichnamigem Theaterstück.' },
    { q:'Welcher Film von Béla Tarr dauert über 7 Stunden?', a:["Werkmeister Harmonies","Satantango","The Turin Horse","Damnation"], c:1, d:3, f:'"Satantango" (1994) — ein episches Panorama des postkommunistischen Ungarns.' },
    { q:'Was bedeutet "mise-en-scène" im Film?', a:["Schnitttechnik","Gesamtgestaltung einer Szene","Kameraführung","Tonspur"], c:1, d:3, f:'Alles im Bild: Licht, Dekoration, Kostüm, Schauspiel, Kameraposition.' },
    { q:'Welcher japanische Regisseur ist bekannt für "Floating Weeds" und "Tokyo Story"?', a:["Akira Kurosawa","Mikio Naruse","Yasujiro Ozu","Kenji Mizoguchi"], c:2, d:3, f:'Ozu drehte meist aus der "Tatami-Perspektive" — Kamera bodennah wie ein sitzender Gast.' },
    { q:'Welcher Film von Alain Resnais zeigt Holocaust-Überlebende und gilt als wichtigster Dokumentarfilm?', a:["Hiroshima Mon Amour","Night and Fog","Muriel","Last Year at Marienbad"], c:1, d:3, f:'"Nacht und Nebel" (1956) — 32 Minuten, die die Welt erschütterten.' },
    { q:'Wer schrieb die Drehbücher zu den meisten Bergman-Filmen?', a:["Nur Bergman selbst","Stig Björkman","Vilgot Sjöman","Ulla Isaksson"], c:0, d:3, f:'Ingmar Bergman schrieb fast alle seine Drehbücher selbst.' },
  ],

  directors: [
    { q:'Bong Joon-hos erster englischsprachiger Film ist...', a:["Snowpiercer","Okja","The Host","Mother"], c:0, d:1, f:'"Snowpiercer" (2013) wurde nachträglich von Harvey Weinstein mit mehr Schnitt-Auflagen belegt — Bong kämpfte dagegen.' },
    { q:'Welcher Regisseur gilt als "Meister des Suspense"?', a:["Billy Wilder","Alfred Hitchcock","Orson Welles","John Huston"], c:1, d:1, f:'Hitchcock drehte über 50 Spielfilme und prägte das Thriller-Genre.' },
    { q:'Terrence Malick verschwand nach "Days of Heaven" (1978) für wie viele Jahre?', a:["5 Jahre","12 Jahre","20 Jahre","28 Jahre"], c:2, d:2, f:'Malick kehrte 1998 mit "Der schmale Grat" zurück — nach 20 Jahren Hollywood-Abwesenheit.' },
    { q:'David Lynchs Spielfilmdebüt "Eraserhead" wurde über wie viele Jahre gedreht?', a:["2 Jahre","5 Jahre","8 Jahre","10 Jahre"], c:1, d:2, f:'Lynch drehte "Eraserhead" von 1971 bis 1977 — oft nur am Wochenende, wegen Geldmangel.' },
    { q:'Wong Kar-wai dreht seine Filme bekanntermaßen ohne...', a:["Drehbuch","Schauspieler","Musik","Schnitt"], c:0, d:2, f:'Wong improvisiert am Set — "In the Mood for Love" entstand aus Tausenden Stunden Footage.' },
    { q:'Für welchen Film gewann Roger Deakins endlich seinen ersten Oscar nach 14 Nominierungen?', a:["No Country for Old Men","Sicario","Blade Runner 2049","1917"], c:2, d:2, f:'Deakins wartete 24 Jahre — von seiner ersten Nominierung für "The Shawshank Redemption" bis zum Sieg.' },
    { q:'Welcher Filmemacher ist bekannt für ungeschnittene "One-Shot" Produktionen und drehte "Victoria" (2015)?', a:["Alfonso Cuarón","Sebastian Schipper","Sam Mendes","Alejandro González Iñárritu"], c:1, d:2, f:'"Victoria" (2015) wurde in einer einzigen 2-stündigen Take gedreht — durch Berlin.' },
    { q:'Alfonso Cuarón drehte "Gravity" mit welchem DoP, bekannt als "El Chivo"?', a:["Roger Deakins","Wally Pfister","Emmanuel Lubezki","Rodrigo Prieto"], c:2, d:2, f:'Lubezkis Arbeit mit Cuarón und später Iñárritu brachte ihm drei Oscar-Siege in Folge.' },
    { q:'Wer führte Regie bei "Mulholland Drive" — und was war das ursprüngliche Format des Projekts?', a:["David Lynch — TV-Pilot für ABC","David Fincher — TV-Serie","David Lynch — Kurzfilm","John Cassavetes — Theaterproduktion"], c:0, d:2, f:'ABC lehnte den Piloten ab — Lynch drehte ihn zu einem Film um, gewann die Goldene Palme.' },
    { q:'Michael Haneke gewann die Goldene Palme zweimal — für welche Filme?', a:["Cache & Funny Games","Das Weiße Band & Liebe","Caché & Das Weiße Band","Funny Games & Liebe"], c:1, d:2, f:'2009 für "Das Weiße Band", 2012 für "Liebe (Amour)" — erst der vierte Regisseur mit zwei Palmen.' },
    { q:'Welcher Regisseur drehte sowohl "Nashville" (1975) als auch "M*A*S*H" (1970)?', a:["Sidney Lumet","Robert Altman","Hal Ashby","John Cassavetes"], c:1, d:2, f:'Robert Altman war für seine Ensemblefilme und improvisierten Dialoge bekannt.' },
    { q:'David Lynch ist auch ausgebildeter...', a:["Arzt","Musiker","Maler","Architekt"], c:2, d:2, f:'Lynch studierte Malerei in Philadelphia — sein visueller Stil zeigt das deutlich.' },
    { q:'Paul Thomas Andersons Spielfilmdebüt (1996) ist bekannt unter zwei Titeln — der ursprüngliche lautet...', a:["Boogie Nights","Hard Eight / Sydney","Punch-Drunk Love","Magnolia"], c:1, d:3, f:'Der Produzent ließ den Film nachträglich umbenennen — PTA hasste den neuen Titel "Hard Eight".' },
    { q:'Stanley Kubrick gewann in seiner gesamten Karriere genau einen Oscar — für was?', a:["2001 (Spezialeffekte)","A Clockwork Orange (Regie)","Barry Lyndon (Regie)","Er gewann nie einen Oscar"], c:3, d:3, f:'Kubrick war 13x nominiert und gewann nie einen Oscar. Nur sein Spezialeffekte-Team für "2001" gewann.' },
    { q:'Welcher Kameramann drehte fast alle Filme von Roger Deakins\'s Lieblings-Regisseur-Duo, den Coen Brothers?', a:["Emmanuel Lubezki","Barry Sonnenfeld + später Roger Deakins selbst","Rodrigo Prieto","Darius Khondji"], c:1, d:3, f:'Barry Sonnenfeld war zuerst ihr DoP — dann übernahm Deakins ab "Barton Fink" (1991).' },
    { q:'Wes Andersons Stammkameramann bei fast allen seinen Filmen ist...', a:["Robert Elswit","Emmanuel Lubezki","Robert Yeoman","Bruno Delbonnel"], c:2, d:3, f:'Yeoman hat seit "Bottle Rocket" (1996) fast jeden Wes Anderson Film fotografiert.' },
    { q:'Spike Lee nennt seine Werke nie "Filme" sondern...', a:["Projects","Joints","Works","Pieces"], c:1, d:3, f:'Spike Lee bezeichnet all seine Werke als "Joints" — seit "She\'s Gotta Have It" (1986).' },
    { q:'"Barry Lyndon" (1974) wurde mit Linsen gedreht, die ursprünglich für welchen Zweck entwickelt wurden?', a:["Astronomie","NASA-Missionen","Medizinische Endoskopie","Militäraufklärung"], c:1, d:3, f:'Die Zeiss-f/0.7-Linsen ermöglichten Kerzenlicht-Aufnahmen — ursprünglich für NASA gebaut.' },
    { q:'Wer sagte: "Film ist 24 mal pro Sekunde Wahrheit"?', a:["Truffaut","Godard","Bazin","Kracauer"], c:1, d:3, f:'Jean-Luc Godard — ein Zitat aus seinem Manifest zur Nouvelle Vague.' },
    { q:'Welcher europäische Regisseur war bekannt dafür, Hunderte von Takes pro Szene zu drehen?', a:["Roman Polanski","Werner Herzog","Stanley Kubrick","Bernardo Bertolucci"], c:2, d:3, f:'Kubrick war berüchtigt für endlose Wiederholungen — z.B. 127 Takes bei Shelley Duvall in The Shining.' },
  ],

  world: [
    { q:'Park Chan-wooks "Oldboy" (2003) ist Teil welcher Trilogie?', a:["Korea-Trilogie","Die Rache-Trilogie","Sympathy Trilogie","Seoul-Trilogie"], c:1, d:2, f:'Die drei Filme sind "Sympathy for Mr. Vengeance", "Oldboy" und "Lady Vengeance".' },
    { q:'Wer spielt die weibliche Hauptrolle in Wong Kar-wais "In the Mood for Love" (2000)?', a:["Zhang Ziyi","Gong Li","Maggie Cheung","Lucy Liu"], c:2, d:2, f:'Maggie Cheung trägt im Film 20 verschiedene Cheongsan-Kleider — eine per Szene.' },
    { q:'Welcher iranische Film von Asghar Farhadi gewann 2012 den Oscar für Besten ausländischen Film?', a:["The Salesman","A Separation","About Elly","Nader and Simin"], c:1, d:2, f:'"A Separation" war der erste iranische Film, der den Oscar für besten fremdsprachigen Film gewann.' },
    { q:'Hirokazu Kore-edas "Shoplifters" gewann 2018 welchen Preis?', a:["Grand Prix Cannes","Goldene Palme","Oscar für Besten Film","Silberner Bär"], c:1, d:2, f:'Kore-eda ist bekannt für seine feinfühligen Familienporträts — oft mit Laiendarstellern.' },
    { q:'Andrei Zvyagintsevs "Leviathan" (2014) gewann den Golden Globe — aus welchem Land?', a:["Ukraine","Russland","Belarus","Georgien"], c:1, d:2, f:'Putin-kritisch interpretiert, wurde der Film in Russland kaum gezeigt.' },
    { q:'"Y Tu Mamá También" (2001) ist bekannt für seinen Einsatz von...', a:["CGI-Effekten","Voice-over Kommentar","Stop-Motion","Schwarzweiß-Fotografie"], c:1, d:2, f:'Cuaróns Voice-over-Kommentator beschreibt ruhig die soziale Realität Mexikos — abseits der Handlung.' },
    { q:'Welcher schwedische Regisseur drehte "The Square" (2017, Goldene Palme)?', a:["Roy Andersson","Ruben Östlund","Lukas Moodysson","Thomas Vinterberg"], c:1, d:2, f:'Östlunds Folgefilm "Triangle of Sadness" gewann 2022 ebenfalls die Goldene Palme.' },
    { q:'Nuri Bilge Ceylan ist bekannt für seine langen, meditativen Dialog-Szenen und kommt aus...', a:["Griechenland","Iran","Türkei","Armenien"], c:2, d:2, f:'"Once Upon a Time in Anatolia" und "Winter Sleep" sind seine bekanntesten Werke.' },
    { q:'Pedro Almodóvars Stammschauspielerin — wer ist sie?', a:["Penélope Cruz","Carmen Maura","Blanca Portillo","Elena Anaya"], c:1, d:2, f:'Carmen Maura spielte in Almodóvars frühen Werken — Penélope Cruz übernahm später diese Rolle.' },
    { q:'Was ist das älteste Filmfestival der Welt?', a:["Cannes","Berlin","Venedig","Sundance"], c:2, d:2, f:'Das Filmfestival Venedig wurde 1932 gegründet.' },
    { q:'Welcher Filmstil nutzt natürliches Licht, Handkamera und nicht-professionelle Schauspieler?', a:["Expressionismus","Surrealismus","Neorealismus","Impressionismus"], c:2, d:2, f:'Der italienische Neorealismus entstand nach dem 2. Weltkrieg mit Regisseuren wie Rossellini und De Sica.' },
    { q:'Béla Tarrs "Sátántangó" (1994) dauert wie lange?', a:["3 Stunden","4,5 Stunden","7,5 Stunden","12 Stunden"], c:2, d:3, f:'Der Film läuft 7,5 Stunden und wurde von Susan Sontag als "Ereignis, nicht Film" beschrieben.' },
    { q:'Welcher Regisseur drehte das südkoreanische Sozialdrama "Burning" (2018), basierend auf Murakami?', a:["Bong Joon-ho","Park Chan-wook","Lee Chang-dong","Hong Sang-soo"], c:2, d:3, f:'"Burning" wurde bei Metacritic zur höchst-bewerteten Cannes-Einreichung aller Zeiten.' },
    { q:'Yasujiro Ozus "Tokyo Story" (1953) nutzt konsequent eine Kamera-Technik — welche?', a:["Hochformat","Tatami-Perspektive (sehr tief)","Dutch Angle","Handkamera"], c:1, d:3, f:'Ozu filmte immer in Augenhöhe von sitzenden Personen — die sogenannte "Tatami-Shot".' },
    { q:'Wie heißt die berühmte iranische Filmschule, die Abbas Kiarostami prägte?', a:["Tehran Film Institute","Kanun","New Iranian Wave","Persian School"], c:1, d:3, f:'"Kanun" (Institut für geistige Entwicklung von Kindern) produzierte Kiarostamis frühe Meisterwerke.' },
    { q:'Welcher japanische Film über drei Schwestern, die eine vierte aufnehmen, lief 2015 in Cannes?', a:["Nobody Knows","Like Father Like Son","Our Little Sister","Shoplifters"], c:2, d:3, f:'Kore-edas "Unsere kleine Schwester" (Umimachi Diary) mit Haruka Ayase und Suzu Hirose.' },
    { q:'Der Begriff "Slow Cinema" beschreibt Regisseure wie Tarr, Akerman und...', a:["Lav Diaz","Quentin Tarantino","Christopher Nolan","Paul Verhoeven"], c:0, d:3, f:'Der philippinische Regisseur Lav Diaz dreht Filme, die oft 8–12 Stunden lang sind.' },
    { q:'Welcher Film wurde als erster der Geschichte farbig präsentiert?', a:["The Jazz Singer","Becky Sharp","Oz","Vitaphone"], c:1, d:3, f:'"Becky Sharp" (1935) war der erste Spielfilm in Technicolor.' },
    { q:'Welcher Film gewann 1955 die Goldene Palme in Cannes und gilt als Meisterwerk?', a:["La Strada","Umberto D.","Bicycle Thieves","Open City"], c:0, d:3, f:'"La Strada" von Federico Fellini — eine poetische Tragödie.' },
    { q:'Was ist die älteste erhaltene Filmkopie der Welt?', a:["Train Arriving at Station","Roundhay Garden Scene","The Kiss","Fred Ott's Sneeze"], c:1, d:3, f:'"Roundhay Garden Scene" (1888) von Louis Le Prince — 2,11 Sekunden lang.' },
  ],

  noir: [
    { q:'Wer führte Regie bei "Chinatown" (1974)?', a:["John Huston","Roman Polanski","Sidney Lumet","Howard Hawks"], c:1, d:1, f:'Jack Nicholson sollte in "Chinatown" ursprünglich Regie führen, entschieden sich aber nur zu schauspielern.' },
    { q:'"Gone Girl" basiert auf dem Roman von...', a:["Gillian Flynn","Tana French","Megan Abbott","Laura Lippman"], c:0, d:1, f:'Gillian Flynn schrieb auch das Drehbuch zur Verfilmung.' },
    { q:'In "Collateral" (2004) — wer spielt den Killer Vincent?', a:["Brad Pitt","Tom Cruise","Javier Bardem","Colin Farrell"], c:1, d:1, f:'Michael Manns "Collateral" wurde digital auf Videokameras gedreht.' },
    { q:'Welcher Coen-Brothers-Film hat Anton Chigurh als Villain?', a:["Blood Simple","Fargo","No Country for Old Men","Miller's Crossing"], c:2, d:1, f:'Javier Bardem gewann für Anton Chigurh den Oscar.' },
    { q:'"Se7en" — was ist im Paket am Ende drin?', a:["Eine Pistole","Nichts","Der Kopf von Mills' Frau","Eine Bombe"], c:2, d:1, f:'David Fincher kämpfte hart für dieses Ende.' },
    { q:'Was ist ein "femme fatale"?', a:["Unschuldige Heldin","Verführerische, gefährliche Frau","Weibliche Detektivin","Unbekannte Täterin"], c:1, d:1, f:'Ein Kernmotiv des Film Noir — die verhängnisvolle Frau, die den Protagonisten ins Verderben zieht.' },
    { q:'Welcher Neo-Noir-Film von David Fincher basiert auf einem Buch von Gillian Flynn?', a:["Se7en","Zodiac","The Girl with the Dragon Tattoo","Gone Girl"], c:3, d:1, f:'"Gone Girl" (2014) — Rosamund Pike gewann für die Rolle eine BAFTA.' },
    { q:'In "Drive" (2011) hat Ryan Goslings Charakter...', a:["Den Namen Ryan","Keinen Namen — nur \"The Driver\"","Den Namen Miles","Den Namen Driver Cole"], c:1, d:2, f:'Goslings Charakter ist bewusst namenlos.' },
    { q:'"L.A. Confidential" (1997) basiert auf einem Roman von...', a:["Raymond Chandler","Elmore Leonard","James Ellroy","James M. Cain"], c:2, d:2, f:'James Ellroys L.A.-Quartett gilt als Höhepunkt des amerikanischen Noir-Romans.' },
    { q:'"Double Indemnity" (1944) gilt als Film-Noir Klassiker — Regie führte...', a:["Howard Hawks","John Huston","Billy Wilder","Orson Welles"], c:2, d:2, f:'Billy Wilder und Raymond Chandler schrieben das Drehbuch gemeinsam.' },
    { q:'In "Mulholland Drive" — welche Farbe hat die geheimnisvolle Box?', a:["Rot","Blau","Gold","Schwarz"], c:1, d:2, f:'Die blaue Box ist eines der rätselhaftesten Symbole in Lynchs Werk.' },
    { q:'"The Third Man" (1949) — wer spielt Harry Lime mit nur 8 Minuten Screentime?', a:["Joseph Cotten","James Mason","Orson Welles","Trevor Howard"], c:2, d:2, f:'Welles improvisierte den berühmten "Kuckucksuhr"-Monolog selbst.' },
    { q:'Welcher Film gilt als einer der ersten "Neo-Noir" Filme?', a:["The Godfather","Chinatown","Taxi Driver","Night Moves"], c:1, d:2, f:'"Chinatown" (1974) dekonstruierte den klassischen Noir.' },
    { q:'Wer spielt in "Blade Runner 2049" die weibliche Joi?', a:["Robin Wright","Ana de Armas","Sylvia Hoeks","Mackenzie Davis"], c:1, d:2, f:'Ana de Armas wurde danach zum neuen Kinostar.' },
    { q:'Wer spielt in "Prisoners" (2013) den Ermittler Detective Loki?', a:["Hugh Jackman","Jake Gyllenhaal","Michael Shannon","Joel Edgerton"], c:1, d:2, f:'Gyllenhaals Loki blinzelt im Film fast nie.' },
    { q:'In welchem Film noir wird "Forget it, Jake — it\'s Chinatown" gesagt?', a:["L.A. Confidential","Chinatown","Who Framed Roger Rabbit","The Two Jakes"], c:1, d:2, f:'Roman Polanskis "Chinatown" (1974) mit Jack Nicholson als Privatdetektiv.' },
    { q:'Denis Villeneuves "Sicario" — wer führte die Kamera?', a:["Roger Deakins","Emmanuel Lubezki","Rodrigo Prieto","Bradford Young"], c:0, d:3, f:'Deakins schuf mit seiner Draufsicht-Einstellung auf die Grenze eine bekannte Szene.' },
    { q:'"Night of the Hunter" (1955) war das einzige Regiewerk von...', a:["John Huston","Charles Laughton","Orson Welles","Elia Kazan"], c:1, d:3, f:'Der Film war bei Erscheinen ein Flop, gilt heute als Meisterwerk.' },
    { q:'Welcher Film noir gilt als erster des Genres?', a:["The Maltese Falcon","Double Indemnity","Laura","This Gun for Hire"], c:0, d:3, f:'"The Maltese Falcon" (1941) mit Humphrey Bogart gilt als Begründer des Genres.' },
    { q:'Welcher Regisseur drehte sowohl "Blade Runner" als auch "L.A. Confidential"?', a:["Michael Mann","James Ellroy","Curtis Hanson","Ridley Scott"], c:2, d:3, f:'Curtis Hanson — nicht Ridley Scott. "L.A. Confidential" (1997) von Curtis Hanson.' },
  ],

  cult: [
    { q:'"The Room" (2003) von Tommy Wiseau gilt als...', a:["Größter Independent-Erfolg","Bestes B-Movie","Eines der schlechtesten Filme ever","Missverstanden"], c:2, d:1, f:'Tommy Wiseau gab Millionen eigenes, rätselhaftes Geld aus.' },
    { q:'Lynch Film mit abgetrenntem Ohr?', a:["Eraserhead","Wild at Heart","Blue Velvet","Lost Highway"], c:2, d:1, f:'Das Ohr leitet in die Unterwelt der USA ein.' },
    { q:'Welcher Film zeigt einen Mann, der am selben Tag immer wieder aufwacht?', a:["Memento","Edge of Tomorrow","Groundhog Day","Source Code"], c:2, d:1, f:'"Groundhog Day" (1993) mit Bill Murray.' },
    { q:'Welcher Film zeigt Kult-Kampfszenen unter dem Markenzeichen "Hai-ya!" mit Bruce Lee?', a:["Enter the Dragon","Fists of Fury","Game of Death","Way of the Dragon"], c:0, d:1, f:'"Enter the Dragon" (1973) war Bruce Lees letzter vollendeter Film.' },
    { q:'"The Rocky Horror Picture Show" läuft im "Cult Loop" seit...', a:["1970","1975","1980","1985"], c:1, d:2, f:'Es ist der längste durchgehende Kino-Lauf eines Films.' },
    { q:'In welchem Jahr spielt "Donnie Darko" (2001)?', a:["1984","1986","1988","1990"], c:2, d:2, f:'Der Film spielt kurz vor der US-Präsidentschaftswahl 1988.' },
    { q:'Welcher Kubrick Film wurde nach Erscheinen in UK verboten?', a:["Lolita","A Clockwork Orange","Barry Lyndon","Spartacus"], c:1, d:2, f:'Kubrick zog ihn selbst aus dem Verleih.' },
    { q:'"Pink Flamingos" (1972) — Divine isst am Ende...', a:["Den Papst","Hundekot","Sich selbst","Einen Flamingo"], c:1, d:2, f:'Eine echte, ungekürzte Szene!' },
    { q:'Paul Verhoevens als Satire missverstandener Film?', a:["Robocop","Total Recall","Starship Troopers","Basic Instinct"], c:2, d:2, f:'Militärs nutzten ihn tatsächlich als Werbung.' },
    { q:'"Hausu" (1977) — aus welchem Land?', a:["Korea","Hong Kong","Japan","Taiwan"], c:2, d:2, f:'Ein psychedelischer Horrortrip.' },
    { q:'Wer spielt Frank Booth in "Blue Velvet"?', a:["Dennis Hopper","Jack Nicholson","Willem Dafoe","Christopher Walken"], c:0, d:2, f:'Ein absolut furchterregender Bösewicht.' },
    { q:'"Naked Lunch" (1991) wurde verfilmt von...', a:["David Cronenberg","David Lynch","Gus Van Sant","Abel Ferrara"], c:0, d:2, f:'Eine brillante Umsetzung der Vorlage.' },
    { q:'Welcher B-Movie-Regisseur ist bekannt für "Plan 9 from Outer Space"?', a:["Roger Corman","Ed Wood","John Waters","Russ Meyer"], c:1, d:2, f:'Ed Wood gilt als "schlechtester Regisseur aller Zeiten" — heute Kultstatus.' },
    { q:'Welcher John Waters Film schockierte mit extremen Inhalten und Drag-Hauptdarstellerin Divine?', a:["Hairspray","Polyester","Pink Flamingos","Female Trouble"], c:2, d:2, f:'"Pink Flamingos" (1972) — berüchtigt für eine Szene, die hier nicht beschrieben wird.' },
    { q:'Welcher Jodorowsky-Film von 1970 gilt als erster "Midnight Movie"?', a:["Holy Mountain","El Topo","Fando y Lis","Santa Sangre"], c:1, d:3, f:'John Lennon finanzierte den Verleih nach einer Privatvorführung.' },
    { q:'In "Blue Velvet" (1986) — wer singt "In Dreams"?', a:["Roy Orbison (Tonträger)","Dennis Hopper live","Isabella Rossellini","Roy Orbison live"], c:0, d:3, f:'Dean Stockwell lip-synct den Song mit einem Garagentor-Dimmer.' },
    { q:'Terry Gilliams "Brazil" (1985) — was machte das Studio ohne ihn?', a:["Sie ließen ihn kolorieren","Sie schnitten ein Happy-End","Sie kürzten ihn","Ein andes Cover"], c:1, d:3, f:'Universal schnitt die 94-minütige "Love Conquers All"-Version.' },
    { q:'"Repo Man" (1984) — wer führte Regie?', a:["John Carpenter","Alex Cox","Joe Dante","Walter Hill"], c:1, d:3, f:'Ein Klassiker des Punkkinos.' },
    { q:'"Natural Born Killers" — Wie viele Filmformate?', a:["2","5","8","Über 10"], c:3, d:3, f:'Oliver Stone trieb die Medienkritik ins Absolute.' },
    { q:'Was ist die "Kuleshov-Wirkung"?', a:["Ein Kamerawinkel","Wechsel aus Nahaufnahme und Totale","Bedeutungsentstehung durch Schnitt zweier Bilder","Ein Soundeffekt"], c:2, d:3, f:'Lew Kuleshov zeigte: Das gleiche Gesicht wirkt anders neben verschiedenen Bildern.' },
  ],

  tech: [
    { q:'"1917" DoP?', a:["Lubezki","Deakins","Kaminski","Young"], c:1, d:1, f:'Deakins holte seinen Zweiten.' },
    { q:'Kamera für "Apocalypse Now"?', a:["Willis","Zsigmond","Storaro","Wexler"], c:2, d:2, f:'Storaro gewann den Oscar.' },
    { q:'Thelma Schoonmaker ist Editorin von...', a:["Spielberg","Coppola","Scorsese","De Palma"], c:2, d:2, f:'3 Oscars für ihre Arbeit.' },
    { q:'Welcher DoP heißt "El Chivo"?', a:["Deakins","Prieto","Lubezki","Kaminski"], c:2, d:2, f:'3 Oscars in Folge!' },
    { q:'DoP bei "Birdman"?', a:["Deakins","Lubezki","Prieto","Morano"], c:1, d:2, f:'Ein scheinbarer Single-Take.' },
    { q:'"Dutch Angle" bedeutet...', a:["Ruhig","Romantisch","Schräg/Desorientierend","Heroisch"], c:2, d:2, f:'Aus dem Expressionismus.' },
    { q:'PTA Score Komponist "There Will Be Blood"?', a:["Greenwood","Williams","Zimmer","Desplat"], c:0, d:2, f:'Jonny Greenwood von Radiohead.' },
    { q:'Was ist eine Plansequenz?', a:["Geplant","Ungeschnitten","Storyboard","Kameratyp"], c:1, d:2, f:'Touch of Evil Opening.' },
    { q:'Was bedeutet "Dolly Zoom" (auch Hitchcock-Zoom)?', a:["Schnelle Kamerabewegung","Gleichzeitiges Zoomen und Gegenfahren","Kreisbewegung der Kamera","Extreme Nahaufnahme"], c:1, d:2, f:'Entwickelt in "Vertigo" (1958) — das Gefühl des Bodens, der unter einem wegzieht.' },
    { q:'Was ist ein "Dutch Angle"?', a:["Sehr ruhige Kameraeinstellung","Romantischer Kamerawinkel","Geneigte, disorientierte Kameraeinstellung","Vogelperspektive"], c:2, d:2, f:'Der Dutch Angle suggeriert psychologische Instabilität oder Bedrohung.' },
    { q:'Welche Technik ermöglichte in "Avatar" (2009) die fotorealistische Darstellung von CGI-Figuren?', a:["Rotoskopie","Performance Capture","Keyframe Animation","3D Scanning"], c:1, d:2, f:'Performance Capture überträgt Mimik und Bewegung eines echten Schauspielers auf CGI-Figuren.' },
    { q:'Linsen bei "Barry Lyndon"?', a:["Canon","Leica","Zeiss/NASA","Nikon"], c:2, d:3, f:'Für Mondmissionen gebaut.' },
    { q:'Morricone und "Dollar-Trilogie"?', a:["Nachher","Vorher","Am Set","Improv"], c:1, d:3, f:'Die Musik gab den Rhythmus vor.' },
    { q:'A/B Bilder Schnitt, der Meaning schafft?', a:["Godard","Kuleshov","Welles","Lang"], c:1, d:3, f:'Der Kuleshov-Effekt.' },
    { q:'DoP "Eyes Wide Shut"?', a:["Willis","Smith","Alcott","Milsome"], c:1, d:3, f:'Viel Kerzenlicht.' },
    { q:'Nolan Editor bis Dunkirk?', a:["Schoonmaker","Smith","Murch","Scalia"], c:1, d:3, f:'Lee Smith!' },
    { q:'Leitmotiv-Erfinder?', a:["Herrmann","Williams","Morricone","Steiner"], c:3, d:3, f:'Max Steiner (King Kong).' },
    { q:'Depth of Field in "Citizen Kane"?', a:["CGI","Blende f/16","Leica","Split"], c:1, d:3, f:'Gregg Toland war revolutionär.' },
    { q:'Welche Kameratechnik wurde in "Birdman" eingesetzt, um den One-Take-Effekt zu erzeugen?', a:["Steadicam","Crane Shot","Scheinbarer Schnittloser Kameralauf","GoPro"], c:2, d:3, f:'Emmanuel Lubezki schnitt subtil an dunklen Momenten und Tonschwellen zusammen.' },
    { q:'Was ist das Verhältnis 2.35:1 im Film?', a:["Tonformat","Seitenformat (Cinemascope)","Framerate","Farbtiefe"], c:1, d:3, f:'Das Anamorphic/Cinemascope-Format — ultra-breit, für epische Panoramen genutzt.' },
  ],

  horror: [
    { q:'"Suspiria" Original Regie?', a:["Argento","Guadagnino","Bava","Fulci"], c:0, d:1, f:'Ein Giallo Masterpiece.' },
    { q:'"Midsommar" Regie?', a:["Ari Aster","Robert Eggers","Jordan Peele","James Wan"], c:0, d:1, f:'Ari Aster!' },
    { q:'Jack Torrance Schauspieler?', a:["Jack Nicholson","Al Pacino","De Niro","Pesci"], c:0, d:1, f:'Heeeere\'s Johnny!' },
    { q:'"Rosemary\'s Baby" Regie?', a:["Polanski","Friedkin","Romero","Carpenter"], c:0, d:1, f:'Mixt Paranoia und Satanismus.' },
    { q:'"Mandy" (2018) Hauptdarsteller?', a:["Cage","Hardy","Isaac","Gosling"], c:0, d:1, f:'Nicolas Cage at his best.' },
    { q:'"The Witch" (2015) — Jahrhundert?', a:["17","18","19","16"], c:0, d:2, f:'Authentisches Neuengland.' },
    { q:'"Hereditary" Dämon?', a:["Baal","Asmodeus","Paimon","Belial"], c:2, d:2, f:'Aus der echten Goetia.' },
    { q:'Begriff für Horror mit Anspruch?', a:["Art House","Post-Horror","Elevated Horror","Social Horror"], c:2, d:2, f:'Oft für A24 Filme genutzt.' },
    { q:'Was ist in "It Follows" das Monster?', a:["Virus","Sexueller Fluch","Geist","Alien"], c:1, d:2, f:'Dauerhaft bedrohlich.' },
    { q:'"Funny Games" bricht was?', a:["Budget","Vierte Wand","Kontinuität","Genre"], c:1, d:2, f:'Der direkte Kamerablick.' },
    { q:'"The Others" (2001) Regisseur?', a:["Del Toro","Bayona","Amenábar","Soderbergh"], c:2, d:2, f:'Mit Nicole Kidman.' },
    { q:'Author of "Haunting of Hill House"?', a:["Jackson","King","Straub","Poe"], c:0, d:2, f:'Shirley Jackson.' },
    { q:'Welcher Film begründete das Slasher-Genre wie wir es kennen?', a:["Psycho","Halloween","The Texas Chain Saw Massacre","Black Christmas"], c:1, d:2, f:'"Halloween" (1978) von John Carpenter mit dem ikonischen Michael Myers.' },
    { q:'Was ist laut Regisseur Ari Aster das zentrale Thema von "Hereditary"?', a:["Teufel","Trauer und Trauma","Besessenheit","Schizophrenie"], c:1, d:2, f:'Aster beschreibt den Film als Familientrauerdrama — der Horror ist Metapher.' },
    { q:'Welche Horror-Reihe begann mit dem Trailer-Park und endete mit 12 Teilen?', a:["Nightmare on Elm Street","Friday the 13th","Halloween","Hellraiser"], c:1, d:2, f:'"Friday the 13th" hat offiziell 12 Kinofilme inklusive Crossover.' },
    { q:'"Don\'t Look Now" Symbolfarbe?', a:["Schwarz","Weiß","Rot","Gelb"], c:2, d:3, f:'Der rote Mantel.' },
    { q:'"Audition" Regie?', a:["Miike","Kurosawa","Park","Bong"], c:0, d:3, f:'Takashi Miike.' },
    { q:'"Possession" (1981) Ort?', a:["Polen","West-Berlin","Paris","London"], c:1, d:3, f:'Mauerstadt.' },
    { q:'Welcher Schauspieler spielte Leatherface in "The Texas Chain Saw Massacre" (1974)?', a:["Gunnar Hansen","Bill Moseley","Ted Levine","Doug Bradley"], c:0, d:3, f:'Gunnar Hansen trug eine echte Maske aus Tierhaut — und litt darunter enorm.' },
    { q:'"Possession" (1981) von Andrzej Zulawski gilt als extremster Horror der europäischen Filmgeschichte — was passiert darin?', a:["Ein Kind wird besessen","Eine Frau entwickelt eine Beziehung zu einem Tentakelwesen","Ein Priester verliert seinen Glauben","Ein Haus erwacht zum Leben"], c:1, d:3, f:'Isabelle Adjani gewann in Cannes — ihre Metrostation-Szene ist legendär.' },
  ],

  indie: [
    { q:'Welche Firma machte Moonlight, Hereditary, EEAAO?', a:["Neon","Blumhouse","A24","Focus"], c:2, d:1, f:'A24.' },
    { q:'Wer gewann Bester Film statt La La Land?', a:["Manchester","Fences","Moonlight","Room"], c:2, d:1, f:'Moonlight.' },
    { q:'Wie lange dauerte Boyhood Dreh?', a:["5","9","12","16"], c:2, d:1, f:'12 Jahre.' },
    { q:'Regie "Everything Everywhere All at Once"?', a:["Russo","Daniels","Safdie","Duplass"], c:1, d:1, f:'Die Daniels.' },
    { q:'Wer spielt in "The Lighthouse"?', a:["Pattinson & Dafoe","Hardy & Isaac","Damon & Wahlberg","Cruise & Pitt"], c:0, d:1, f:'Zwei Leuchtturmwärter.' },
    { q:'Welches Studio produzierte "Moonlight" und "Everything Everywhere All at Once"?', a:["Neon","Blumhouse","A24","Focus Features"], c:2, d:1, f:'A24 ist das prestige-reichste Independent-Studio der Gegenwart.' },
    { q:'Welche Regisseurin drehte "Lady Bird" (2017)?', a:["Sofia Coppola","Greta Gerwig","Lena Dunham","Ari Aster"], c:1, d:1, f:'Greta Gerwigs Regiedebüt wurde für 5 Oscars nominiert.' },
    { q:'In welchem Film verbringt Richard Linklater eine Nacht mit einer Fremden in Wien?', a:["Before Sunset","Before Midnight","Before Sunrise","Before Dawn"], c:2, d:1, f:'"Before Sunrise" (1995) — Teil 1 der romantischen Trilogie.' },
    { q:'Safdie Brothers Filme spielen oft in...', a:["LA","New York","Chicago","Texas"], c:1, d:2, f:'Pures NY-Streetfeel.' },
    { q:'"Aftersun" Regie?', a:["Song","Wells","Hansen-Løve","Reichardt"], c:1, d:2, f:'Charlotte Wells.' },
    { q:'"Past Lives" Regie?', a:["Wells","Song","Kogonada","Aster"], c:1, d:2, f:'Celine Song.' },
    { q:'"Tangerine" Kamera?', a:["iPhone 5S","GoPro","DSLR","Red"], c:0, d:2, f:'iPhone pur.' },
    { q:'"Florida Project" Regie?', a:["Baker","Safdie","Aster","Linklater"], c:0, d:2, f:'Sean Baker.' },
    { q:'"Minari" Hauptsprache?', a:["Englisch","Koreanisch","Beides","Spanisch"], c:1, d:2, f:'Koreanisch.' },
    { q:'"Saint Maud" Genre?', a:["Rom-Com","Horror","Sci-Fi","Drama"], c:1, d:2, f:'Psychologischer Horror.' },
    { q:'Van Sant Film ohne Dialog?', a:["Idaho","Gerry","Elephant","Milk"], c:1, d:3, f:'Gerry.' },
    { q:'Kelly Reichardt Stil?', a:["Fast","Slow Cinema","Action","Found Footage"], c:1, d:3, f:'Slow Cinema.' },
    { q:'"Parasite" Studio?', a:["CJ / Barunson","A24","Neon","Lotte"], c:0, d:3, f:'Südkorea.' },
    { q:'Was ist das Hauptmerkmal des "Mumblecore"-Genres?', a:["Extreme Gewalt","Improvisiertes Gespräch und Low Budget","Sci-Fi-Ästhetik","Dokumentarfilm-Stil"], c:1, d:3, f:'Mumblecore (2000er) — Filme wie "Hannah Takes the Stairs" von Joe Swanberg.' },
    { q:'Wer drehte "Beasts of the Southern Wild" (2012)?', a:["Benh Zeitlin","Jeff Nichols","David Gordon Green","Lance Hammer"], c:0, d:3, f:'Benh Zeitlin drehte den Film für 1,8 Mio. Dollar — für 4 Oscars nominiert.' },
  ],

  // --- NEUE KATEGORIEN ---
  series: [
    { q:'Wer spielt Heisenberg in Breaking Bad?', a:["Bryan Cranston","Aaron Paul","Bob Odenkirk","Giancarlo Esposito"], c:0, d:1, f:'Bryan Cranston machte Walter White unsterblich.' },
    { q:'Wie heißt die Hauptfamilie in "The Sopranos"?', a:["Corleone","Soprano","Moltisanti","Gualtieri"], c:1, d:1, f:'Tony Soprano revolutionierte die Fernsehgeschichte.' },
    { q:'Welche Farbe haben die Anzüge der Wächter in "Squid Game"?', a:["Blau","Pink/Rot","Grün","Gelb"], c:1, d:1, f:'Die gruseligen Wärter tragen knallige Farben.' },
    { q:'Welche Plattform produzierte "House of Cards" (US)?', a:["HBO","Amazon","Netflix","Hulu"], c:2, d:1, f:'House of Cards war eine der ersten großen Netflix-Eigenproduktionen.' },
    { q:'Wer spielt den Anwalt Saul Goodman in "Better Call Saul"?', a:["Bryan Cranston","Aaron Paul","Bob Odenkirk","Jonathan Banks"], c:2, d:1, f:'Bob Odenkirk spielte die Rolle schon in Breaking Bad.' },
    { q:'In welcher Serie tauchen die Begriffe "Upside Down" und "Demogorgon" auf?', a:["Dark","Stranger Things","Fringe","Lost"], c:1, d:1, f:'Stranger Things ist stark von 80er-Horrorfilmen inspiriert.' },
    { q:'Wer schrieb die Romanvorlage zu "Game of Thrones"?', a:["J.R.R. Tolkien","George R.R. Martin","Stephen King","Neil Gaiman"], c:1, d:1, f:'"A Song of Ice and Fire" — bis heute unvollendet.' },
    { q:'In welcher Serie spielt Emilia Clarke Daenerys Targaryen?', a:["The Witcher","Game of Thrones","Westworld","Outlander"], c:1, d:1, f:'Game of Thrones war ein kulturelles Phänomen.' },
    { q:'Welche koreanische Serie wurde das meistgesehene Netflix-Original aller Zeiten?', a:["Hellbound","All of Us Are Dead","Squid Game","Kingdom"], c:2, d:1, f:'Squid Game brach alle Netflix-Rekorde.' },
    { q:'In welcher Serie dreht sich alles um Drogenkartelle in Kolumbien?', a:["Ozark","Narcos","The Wire","Peaky Blinders"], c:1, d:1, f:'Narcos basiert auf dem Leben von Pablo Escobar.' },
    { q:'Welche Serie handelt von einem Zeitreise-Paradoxon in der deutschen Provinz?', a:["Babylon Berlin","Dark","Kleo","Dogs of Berlin"], c:1, d:1, f:'Dark war Deutschlands erstes globales Netflix-Phänomen.' },
    { q:'Wer spielt den Gangsterboss in "Peaky Blinders"?', a:["Tom Hardy","Cillian Murphy","Paul Anderson","Sam Neill"], c:1, d:1, f:'Cillian Murphy als Tommy Shelby wurde zur Ikone.' },
    { q:'Welche Serie drehte sich um einen Manipulator namens Frank Underwood?', a:["Veep","Scandal","House of Cards","Suits"], c:2, d:1, f:'"House of Cards" mit Kevin Spacey — wurde 2018 nach Vorwürfen abgebrochen.' },
    { q:'In welcher HBO-Serie werden Fantasie-Welten von "Hosts" (Androiden) bevölkert?', a:["Lovecraft Country","Euphoria","Westworld","The Leftovers"], c:2, d:1, f:'"Westworld" — basierend auf Michael Crichtons Film von 1973.' },
    { q:'Welche Serie zeigt das Leben von Ballerina-Mörderinnen in einer schwarzen Komödie?', a:["Killing Eve","Fleabag","Dead to Me","The Americans"], c:0, d:1, f:'"Killing Eve" mit Sandra Oh und Jodie Comer.' },
    { q:'"The Wire" spielt in welcher amerikanischen Stadt?', a:["New York","Chicago","Baltimore","Los Angeles"], c:2, d:2, f:'Baltimore dient als Spiegel für das gesamte amerikanische System.' },
    { q:'In "Chernobyl" (HBO) — was war der tatsächliche Unglücksort?', a:["Russland","Weißrussland","Ukraine","Polen"], c:2, d:2, f:'Das Kernkraftwerk Tschernobyl liegt in der heutigen Ukraine.' },
    { q:'Welche Serie zeigt das Leben im Weißen Haus unter Präsident Bartlet?', a:["House of Cards","Veep","The West Wing","Scandal"], c:2, d:2, f:'The West Wing von Aaron Sorkin gilt als idealistisches Politdrama.' },
    { q:'In welcher Serie lautet das Passwort "Winter is Coming"?', a:["Game of Thrones","The Last of Us","The Witcher","Westworld"], c:0, d:2, f:'Der Spruch des Hauses Stark ist das Symbol für drohende Gefahr.' },
    { q:'Wer ist die Showrunnerin der Serie "Fleabag"?', a:["Lena Dunham","Michaela Coel","Phoebe Waller-Bridge","Amy Sherman-Palladino"], c:2, d:2, f:'Phoebe Waller-Bridge schrieb, produzierte und spielte die Hauptrolle.' },
  ],

  animation: [
    { q:'Welcher Pixar-Film spielt primär im Kopf eines Mädchens?', a:["Soul","Up","Inside Out","Coco"], c:2, d:1, f:'Alles steht Kopf visualisiert Emotionen großartig.' },
    { q:'Wer ist der Protagonist der Spider-Verse Filme?', a:["Peter Parker","Miles Morales","Miguel O'Hara","Gwen Stacy"], c:1, d:1, f:'Miles Morales bringt unglaublichen Style.' },
    { q:'Welches Studio produzierte "WALL-E"?', a:["DreamWorks","Pixar","Disney","Laika"], c:1, d:1, f:'Pixar ist seit 1986 Teil von Disney.' },
    { q:'Welcher Pixar-Film war der erste vollständig computeranimierte Spielfilm?', a:["A Bug's Life","Toy Story","Monsters Inc.","Cars"], c:1, d:1, f:'Toy Story (1995) revolutionierte die Animationsgeschichte.' },
    { q:'Welcher Zeichentrickfilm beginnt mit dem Tod der Mutter des Protagonisten?', a:["Bambi","Dumbo","The Lion King","Finding Nemo"], c:0, d:1, f:'Bambis Mutter ist eines der traumatischsten Filmereignisse der Kindheit.' },
    { q:'In "Ratatouille" — was ist Remys große Leidenschaft?', a:["Backen","Kochen","Tanzen","Malen"], c:1, d:1, f:'Eine Ratte will der beste Koch von Paris werden.' },
    { q:'In "Up" — womit beginnt der Film emotional?', a:["Tod des Hundes","Kurze Liebesgeschichte über ein ganzes Leben","Abenteuerkarte","Ballonstart"], c:1, d:1, f:'Die erste Viertelstunde ohne Dialog gilt als emotionalste Szenenfolge Pixars.' },
    { q:'Welcher Studio-Ghibli-Film handelt von zwei Schwestern und einem riesigen Waldgeist?', a:["Prinzessin Mononoke","Chihiros Reise","Mein Nachbar Totoro","Nausicaä"], c:2, d:1, f:'Totoro ist das bekannteste Symbol von Studio Ghibli.' },
    { q:'Welcher DreamWorks-Film startet mit einem Esel, der Lieder singt?', a:["Shrek","Madagascar","Kung Fu Panda","How to Train Your Dragon"], c:0, d:1, f:'Eddie Murphy als Donkey ist einer der beliebtesten Animationscharaktere.' },
    { q:'In welchem Pixar-Film werden Erinnerungen als Kugeln dargestellt?', a:["Soul","Up","Inside Out","Coco"], c:2, d:1, f:'"Alles steht Kopf" / "Inside Out" — Emotionen steuern das Innenleben.' },
    { q:'Welches Miyazaki-Meisterwerk gewann einen Oscar?', a:["Prinzessin Mononoke","Chihiros Reise ins Zauberland","Mein Nachbar Totoro","Das wandelnde Schloss"], c:1, d:2, f:'Spirited Away gewann 2003.' },
    { q:'Welcher Anime-Film von Satoshi Kon handelt von einer Sängerin und einem Stalker?', a:["Paprika","Millennium Actress","Tokyo Godfathers","Perfect Blue"], c:3, d:2, f:'Perfect Blue beeinflusste Darren Aronofskys "Black Swan".' },
    { q:'Welcher Anime-Regisseur ist bekannt für "Akira" (1988)?', a:["Hayao Miyazaki","Katsuhiro Otomo","Isao Takahata","Mamoru Oshii"], c:1, d:2, f:'Akira revolutionierte die westliche Wahrnehmung von Anime.' },
    { q:'"The Incredibles" wurde von welchem Regisseur gedreht?', a:["Andrew Stanton","Pete Docter","Brad Bird","John Lasseter"], c:2, d:2, f:'Brad Bird drehte vorher schon The Iron Giant.' },
    { q:'Welcher Film läutete die Disney-Renaissance der 90er ein?', a:["The Little Mermaid","Beauty and the Beast","Aladdin","The Lion King"], c:0, d:2, f:'"Arielle" (1989) rettete das Disney-Animationsstudio.' },
    { q:'Welcher Spider-Verse-Film gewann 2023 den Annie Award für Besten Animationsfilm?', a:["Into the Spider-Verse","Across the Spider-Verse","Beyond the Spider-Verse","Spider-Man: No Way Home"], c:1, d:2, f:'Across the Spider-Verse beeindruckte mit neuen Animationsstilen.' },
    { q:'Welcher Disney-Animationsfilm basiert auf Hans Christian Andersens Geschichte?', a:["Cinderella","Snow White","The Little Mermaid","Sleeping Beauty"], c:2, d:2, f:'"Arielle" basiert auf Andersens "Die kleine Seejungfrau" — allerdings mit Happy End.' },
    { q:'Wer ist der Gründer von Studio Ghibli?', a:["Isao Takahata (allein)","Hayao Miyazaki (allein)","Miyazaki und Takahata gemeinsam","Satoshi Kon"], c:2, d:2, f:'Ghibli wurde 1985 von Miyazaki, Takahata und dem Produzenten Suzuki gegründet.' },
    { q:'Welcher Stop-Motion-Regisseur ist bekannt für "Corpse Bride" und "Coraline"?', a:["Nick Park","Henry Selick","Tim Burton","Laika Studio"], c:1, d:3, f:'Henry Selick drehte "Coraline" (2009) und "The Nightmare Before Christmas".' },
    { q:'Was war der erste Anime, der in den USA kommerziell im Kino erfolgreich war?', a:["Dragon Ball Z","Ghost in the Shell","Akira","Princess Mononoke"], c:2, d:3, f:'"Akira" (1988) öffnete die Tür für Anime im Westen.' },
  ],

  superhero: [
    { q:'Wer führte Regie bei "The Dark Knight"?', a:["Zack Snyder","Christopher Nolan","Tim Burton","Matt Reeves"], c:1, d:1, f:'Nolan veränderte das Genre für immer.' },
    { q:'Wer spielte in "Joker" (2019) die Hauptrolle?', a:["Heath Ledger","Jared Leto","Joaquin Phoenix","Jack Nicholson"], c:2, d:1, f:'Phoenix gewann dafür den Oscar.' },
    { q:'Welcher Schauspieler verkörperte Iron Man im MCU?', a:["Chris Evans","Chris Hemsworth","Robert Downey Jr.","Mark Ruffalo"], c:2, d:1, f:'Downey Jr. schlüpfte von 2008 bis 2019 in den Anzug.' },
    { q:'Welche Figur ist bekannt für den Satz "I am Groot"?', a:["Rocket","Drax","Groot","Gamora"], c:2, d:1, f:'Groot kommuniziert ausschließlich mit drei Worten.' },
    { q:'Welcher X-Men ist bekannt für seine unzerstörbaren Adamantium-Knochen?', a:["Cyclops","Storm","Wolverine","Magneto"], c:2, d:1, f:'Hugh Jackman spielte Wolverine 17 Jahre lang.' },
    { q:'Welche Superheldin hat einen magischen Lasso der Wahrheit?', a:["Supergirl","Black Widow","She-Hulk","Wonder Woman"], c:3, d:1, f:'Wonder Woman wurde 1941 erfunden.' },
    { q:'"Deadpool" ist bekannt dafür, dass er...', a:["nie flucht","die vierte Wand bricht","immer die Welt rettet","keine Waffen trägt"], c:1, d:1, f:'Deadpool spricht direkt mit dem Publikum — Meta-Humor pur.' },
    { q:'Welcher Superheld wird von T\'Challa verkörpert?', a:["Captain America","Black Panther","Falcon","Blade"], c:1, d:1, f:'Black Panther (2018) war ein kultureller Meilenstein.' },
    { q:'In welcher Stadt lebt Spider-Man?', a:["Gotham City","Metropolis","New York City","Central City"], c:2, d:1, f:'Peter Parker / Miles Morales — beide aus New York.' },
    { q:'Wer spielt Thor im MCU?', a:["Chris Evans","Chris Hemsworth","Chris Pratt","Chris Pine"], c:1, d:1, f:'Chris Hemsworth debütierte 2011 als Donnergott.' },
    { q:'Welcher Schauspieler spielte Superman in "Man of Steel"?', a:["Brandon Routh","Tom Welling","Henry Cavill","Tyler Hoechlin"], c:2, d:1, f:'Henry Cavill debütierte 2013 als Superman in Zack Snyders Reboot.' },
    { q:'Was ist die erste Regel des Spidermans?', a:["Keine Schule verpassen","Mit großer Kraft kommt große Verantwortung","Maske nie abnehmen","Immer alleine kämpfen"], c:1, d:1, f:'Mit großer Kraft kommt große Verantwortung — Uncle Ben\'s Vermächtnis.' },
    { q:'Welcher Marvel-Film hatte als erster über 2 Milliarden Dollar Einspiel?', a:["Avengers","Infinity War","Endgame","Black Panther"], c:1, d:2, f:'Infinity War war ein massiver Meilenstein.' },
    { q:'Wer schrieb die Comicvorlage zu "Watchmen"?', a:["Stan Lee","Alan Moore","Frank Miller","Neil Gaiman"], c:1, d:2, f:'"Watchmen" gilt als wichtigstes Comic-Werk überhaupt.' },
    { q:'In "Avengers: Endgame" — wer opfert sich für den Soul Stone?', a:["Tony Stark","Thanos","Black Widow","Gamora"], c:2, d:2, f:'Natasha Romanoff opfert sich auf Vormir.' },
    { q:'Welcher Schauspieler spielte als erster Batman in einem modernen Blockbuster?', a:["Christian Bale","Michael Keaton","George Clooney","Val Kilmer"], c:1, d:2, f:'Michael Keaton spielte Batman 1989 unter Tim Burton.' },
    { q:'In welchem Film erscheint Nick Fury nach dem Credits zur Avengers-Initiative?', a:["Thor","Captain America","Iron Man","The Incredible Hulk"], c:2, d:2, f:'Iron Man (2008) startete das MCU mit der berühmten Post-Credits-Szene.' },
    { q:'Welcher Schauspieler spielt in "Black Panther" die Rolle des Gegners Killmonger?', a:["Idris Elba","Michael B. Jordan","Winston Duke","Daniel Kaluuya"], c:1, d:2, f:'Michael B. Jordan als Erik Killmonger — einer der besten MCU-Antagonisten.' },
    { q:'In welchem Marvel-Film erscheint zum ersten Mal die "Infinity Gauntlet"?', a:["Avengers: Infinity War","Avengers: Age of Ultron","Thor: The Dark World","Guardians of the Galaxy"], c:1, d:3, f:'Am Ende von "Age of Ultron" (2015) erscheint Thanos mit dem leeren Handschuh.' },
    { q:'Welche DC-Figur wird von ihrer Adoptivmutter zu Herkules Kraft trainiert?', a:["Supergirl","Wonder Woman","Batgirl","Zatanna"], c:1, d:3, f:'Wonder Woman wurde von Queen Hippolyta und der Amazon-Kriegerinnengilde ausgebildet.' },
  ],

  oscars: [
    { q:'Welcher fremdsprachige Film gewann als erster "Best Picture"?', a:["Roma","Parasite","Amelie","Life is Beautiful"], c:1, d:1, f:'Parasite schrieb 2020 Geschichte.' },
    { q:'Welches fremdsprachige Land feierte 2020 den Triumph bei der Oscar-Zeremonie?', a:["Japan","China","Südkorea","Thailand"], c:2, d:1, f:'Parasite aus Südkorea räumte 2020 ab.' },
    { q:'Welcher Film gewann 2023 den Oscar für "Besten Film"?', a:["Tár","The Fabelmans","Everything Everywhere All at Once","Banshees of Inisherin"], c:2, d:1, f:'"Everything Everywhere All at Once" gewann 7 Oscars, darunter Besten Film.' },
    { q:'Welcher Film gewann die meisten Oscars (11)?', a:["Titanic","Ben-Hur","Lord of the Rings 3","Alle drei"], c:3, d:2, f:'Alle drei halten den Rekord mit je 11 Oscars.' },
    { q:'Welcher Schauspieler hat die meisten Oscar-Nominierungen?', a:["Jack Nicholson","Meryl Streep","Katharine Hepburn","Spencer Tracy"], c:1, d:2, f:'Meryl Streep wurde 21 Mal nominiert.' },
    { q:'Wer moderierte die "Slap"-Oscar-Nacht 2022?', a:["Jimmy Kimmel","Seth MacFarlane","Chris Rock","Billy Crystal"], c:2, d:2, f:'Will Smith schlug Chris Rock auf offener Bühne.' },
    { q:'Welcher Schauspieler gewann für "Philadelphia" seinen ersten Oscar?', a:["Dustin Hoffman","Tom Hanks","Denzel Washington","Morgan Freeman"], c:1, d:2, f:'Tom Hanks gewann 1993 und 1994 gleich zwei Mal in Folge.' },
    { q:'Welcher Eastwood-Film gewann 2005 "Besten Film" und "Beste Regie"?', a:["Mystic River","Gran Torino","Million Dollar Baby","Unforgiven"], c:2, d:2, f:'Million Dollar Baby — ein Boxerfilm über Verlust und Würde.' },
    { q:'Wie heißt die Verleihorganisation hinter den Oscars?', a:["BAFTA","Academy of Motion Picture Arts and Sciences","Hollywood Foreign Press","SAG"], c:1, d:2, f:'Die AMPAS wurde 1927 gegründet.' },
    { q:'Welcher Film von Alfonso Cuarón gewann 2014 sieben Oscars?', a:["Children of Men","Y Tu Mamá También","Gravity","Roma"], c:2, d:2, f:'Gravity gewann u.a. Bester Regisseur und Bester Schnitt.' },
    { q:'Wer gewann den Oscar für "Beste Regie" für "The Hurt Locker"?', a:["James Cameron","Quentin Tarantino","Kathryn Bigelow","Christopher Nolan"], c:2, d:2, f:'Kathryn Bigelow war die erste Frau, die den Regie-Oscar gewann.' },
    { q:'Wer war die erste schwarze Frau, die den Oscar für "Beste Regie" gewann?', a:["Ava DuVernay","Gina Prince-Bythewood","Regina King","Noch niemand"], c:3, d:2, f:'Bis 2024 hat noch keine schwarze Frau diesen Oscar gewonnen.' },
    { q:'Wer hat die meisten Oscars für "Beste Regie"?', a:["Steven Spielberg","John Ford","Katharine Hepburn","Walt Disney"], c:1, d:3, f:'John Ford hat 4 Oscars für Regie.' },
    { q:'Welcher Schauspieler gewann dreimal den Oscar — als einziger?', a:["Daniel Day-Lewis","Jack Nicholson","Walter Brennan","Katharine Hepburn"], c:0, d:3, f:'Daniel Day-Lewis ist der einzige dreifache Gewinner als Schauspieler.' },
    { q:'In welchem Jahr wurde die Oscar-Kategorie "Bester Animationsfilm" eingeführt?', a:["1990","1995","2002","2008"], c:2, d:3, f:'2002 gewann "Shrek" als erster Film diese neue Kategorie.' },
    { q:'Welcher Film war 1985 elf Mal nominiert und gewann keinen einzigen Oscar?', a:["The Aviator","American Hustle","The Color Purple","True Grit"], c:2, d:3, f:'"The Color Purple" hält den traurigen Rekord der meisten Niederlagen.' },
    { q:'Welcher Pixar-Kurzfilm war der erste, der einen Oscar gewann?', a:["Tin Toy","Luxo Jr.","Geri's Game","For the Birds"], c:0, d:3, f:'Tin Toy (1988) war das erste Oscar-prämierte computergenerierte Werk.' },
    { q:'Welcher Film hat den Rekord für die meisten Oscars OHNE zu gewinnen?', a:["Gangs of New York","The Color Purple","The Turning Point","Tutti Frutti"], c:1, d:3, f:'"The Color Purple" (1985) — 11 Nominierungen, 0 Gewinne.' },
    { q:'In welchem Jahr weigerten sich Sachverständige erstmals, einen Oscar zu vergeben?', a:["1933","1962","1994","2003"], c:1, d:3, f:'1962 wurde kein Oscar für "Besten fremdsprachigen Film" vergeben — zu wenige Einreichungen.' },
    { q:'Welcher Film erhielt als einziger eine Hauptdarsteller- UND Hauptdarstellerin-Nominierung für dieselbe Figur?', a:["Tootsie","Some Like it Hot","Mrs. Doubtfire","Keine"], c:3, d:3, f:'Bisher gab es das nicht — es wäre aber denkbar bei Genderswap-Rollen.' },
  ],

  german: [
    { q:'Welcher Film gewann den Oscar für den besten fremdsprachigen Film 2023?', a:["Lola rennt","Das weiße Band","Im Westen nichts Neues","Toni Erdmann"], c:2, d:1, f:'Im Westen Nichts Neues.' },
    { q:'Wie heißt die erste deutsche Netflix-Originalserie?', a:["How to Sell Drugs Online","Dark","Babylon Berlin","Kleo"], c:1, d:1, f:'Dark ist ein globales Phänomen.' },
    { q:'Wer spielte die Hauptrolle in "Lola rennt"?', a:["Martina Gedeck","Franka Potente","Sandra Hüller","Diane Kruger"], c:1, d:1, f:'Franka Potente rannte durch das Berlin der 90er.' },
    { q:'Welcher Film über die DDR-Staatssicherheit gewann 2007 den Oscar?', a:["Das Leben der Anderen","Good Bye Lenin","Sonnenallee","Barbara"], c:0, d:1, f:'"Das Leben der Anderen" von Florian Henckel von Donnersmarck.' },
    { q:'Welcher deutsche Schauspieler spielte Hitler in "Der Untergang"?', a:["Ulrich Mühe","Bruno Ganz","Moritz Bleibtreu","Til Schweiger"], c:1, d:1, f:'Bruno Ganz verkörperte Hitler in den letzten Kriegstagen.' },
    { q:'Welcher Filmfestivalpreis wird in Berlin verliehen?', a:["Goldene Palme","Goldener Löwe","Goldener Bär","Goldene Kamera"], c:2, d:1, f:'Der Goldene Bär der Berlinale ist einer der renommiertesten Filmpreise.' },
    { q:'Wer führte Regie beim deutschen Kultfilm "Lola rennt" (1998)?', a:["Fatih Akin","Tom Tykwer","Dani Levy","Wolfgang Petersen"], c:1, d:1, f:'Tom Tykwer schrieb und inszenierte den Experimentalfilm.' },
    { q:'Wer führte Regie bei "Victoria" (One-Shot Film)?', a:["Fatih Akin","Tom Tykwer","Sebastian Schipper","Christian Petzold"], c:2, d:2, f:'Schipper drehte in einem einzigen Take.' },
    { q:'Welcher berühmte Regisseur drehte "Das Boot"?', a:["Werner Herzog","Wim Wenders","Wolfgang Petersen","Volker Schlöndorff"], c:2, d:2, f:'"Das Boot" (1981) ist einer der bekanntesten deutschen Kriegsfilme.' },
    { q:'Welcher Regisseur drehte "Aguirre, der Zorn Gottes" im Amazonas?', a:["Wim Wenders","Rainer Werner Fassbinder","Werner Herzog","Edgar Reitz"], c:2, d:2, f:'Herzog drehte den Film unter extremen Bedingungen im Regenwald.' },
    { q:'Fatih Akıns Film "Gegen die Wand" gewann welchen Preis?', a:["Oscar","Goldene Palme","Goldenen Bären","César"], c:2, d:2, f:'"Gegen die Wand" (2004) gewann den Goldenen Bären der Berlinale.' },
    { q:'Maren Ade drehte das für den Oscar nominierte deutsche Drama...', a:["Hannah Arendt","Toni Erdmann","Styx","Schwesterlein"], c:1, d:2, f:'Toni Erdmann (2016) war für den Fremdsprachigen Film-Oscar nominiert.' },
    { q:'Welcher Film zeigt Schüler in einem Weimarer Internat unter kaiserlichem Druck?', a:["Das weiße Band","Die Welle","Das Lehrerzimmer","Nackte Tiere"], c:0, d:2, f:'Michael Hanekes "Das weiße Band" gewann 2009 die Goldene Palme.' },
    { q:'Wer produzierte und schrieb die deutsche Kultserie "Babylon Berlin"?', a:["Tom Tykwer","Fatih Akin","Sebastian Schipper","Wolfgang Petersen"], c:0, d:2, f:'Tom Tykwer co-produzierte und -schrieb die Serie.' },
    { q:'Welche deutsche Schauspielerin gewann den Oscar für "Beste Darstellerin" für "The Reader"?', a:["Diane Kruger","Franka Potente","Kate Winslet","Sandra Hüller"], c:2, d:2, f:'Kate Winslet ist Britin, spielte aber eine Deutsche. Fangfrage!' },
    { q:'Welcher Film von Christian Petzold spielt in der NS-Zeit nach dem Krieg?', a:["Barbara","Phoenix","Yella","Transit"], c:1, d:3, f:'"Phoenix" (2014) — eine Frau kehrt entstellt aus dem KZ zurück.' },
    { q:'Welches deutsche Regisseursehepaar ist bekannt für Krimifilme mit Tatort-Ästhetik?', a:["Nico und Jessica Hoffmann","Ulrich und Barbara Seidl","Dominik Graf","Anna und Frank Buchwald"], c:2, d:3, f:'Dominik Graf gilt als einer der besten deutschen Genrefilmer.' },
    { q:'Welcher Regisseur der "Berliner Schule" ist bekannt für "Toter Mann" und "Yella"?', a:["Angela Schanelec","Thomas Arslan","Christoph Hochhäusler","Christian Petzold"], c:3, d:3, f:'Christian Petzold gilt als wichtigste Stimme der Berliner Schule.' },
    { q:'Welches Thema ist Hauptgegenstand von Rainer Werner Fassbinders Werk?', a:["Krieg","Liebe als Machtinstrument","Religion","Science Fiction"], c:1, d:3, f:'Fassbinder untersuchte wie Liebe genutzt wird um Menschen zu kontrollieren und zu zerstören.' },
    { q:'In welchem Film erscheint der Begriff "Vergangenheitsbewältigung" als zentrales Thema?', a:["Das weiße Band","Der Untergang","Hannah Arendt","Sophie Scholl"], c:2, d:3, f:'"Hannah Arendt" (2012) von Margarethe von Trotta — über das Eichmann-Tribunal.' },
  ],

  comedy: [
    { q:'Wer spielt in "Der große Diktator" (1940) einen Hitler-ähnlichen Diktator?', a:["Charlie Chaplin","Buster Keaton","Harold Lloyd","Marx Brothers"], c:0, d:1, f:'Chaplin verhöhnte Hitler mutig auf offener Leinwand.' },
    { q:'Wer spielte in "The Grand Budapest Hotel" den Concierge Gustave H.?', a:["Bill Murray","Jeff Goldblum","Ralph Fiennes","Tilda Swinton"], c:2, d:1, f:'Wes Andersons skurrile Komödie vereint einen riesigen Starcast.' },
    { q:'Wer drehte "Annie Hall" (1977)?', a:["Sidney Lumet","Woody Allen","Mike Nichols","Robert Altman"], c:1, d:1, f:'"Annie Hall" gewann den Oscar für Bester Film und Beste Regie.' },
    { q:'Welcher Film mit Steve Carell wurde ein Überraschungshit über einen 40-Jährigen?', a:["Get Smart","Date Night","The 40-Year-Old Virgin","Anchorman"], c:2, d:1, f:'"The 40-Year-Old Virgin" (2005) startete Carells Karriere als Komödien-Star.' },
    { q:'In "Knives Out" dreht sich alles um einen...', a:["Raubüberfall","Mordfall","Erbschaftsstreit","Kunstdiebstahl"], c:1, d:1, f:'"Knives Out" (2019) ist ein moderner Whodunit-Krimi.' },
    { q:'In welchem Kultfilm antwortet Ferris Bueller direkt ins Publikum?', a:["Ferris macht blau","Breakfast Club","Footloose","Pretty in Pink"], c:0, d:1, f:'John Hughes Kultfilm von 1986.' },
    { q:'Welcher Sketch-Film von Monty Python handelt von Rittern und Kokosnüssen?', a:["Life of Brian","Monty Python and the Holy Grail","The Meaning of Life","And Now for Something Completely Different"], c:1, d:1, f:'"Monty Python and the Holy Grail" (1975) mit minimalem Budget.' },
    { q:'Welcher Schauspieler spielte den Detektiven Frank Drebin, den Präsidenten und Filmstar in Komödien?', a:["Steve Martin","Leslie Nielsen","Chevy Chase","John Belushi"], c:1, d:1, f:'Leslie Nielsen wechselte von ernsthaften Rollen zur Komödie und wurde Kult.' },
    { q:'In welchem Film wird das "Ministerium für alberne Gänge" parodiert?', a:["Life of Brian","Holy Grail","Flying Circus","Meaning of Life"], c:2, d:2, f:'Monty Pythons Flying Circus war eine Serie, kein Film, aber absolut ikonisch.' },
    { q:'Welcher Film endet mit "Nobody is perfect"?', a:["Some Like It Hot","Airplane!","Annie Hall","Dumb and Dumber"], c:0, d:2, f:'Manche mögen\'s heiß.' },
    { q:'Wer führte Regie bei "Dr. Strangelove" (1964)?', a:["Billy Wilder","Stanley Kubrick","Mel Brooks","Woody Allen"], c:1, d:2, f:'"Dr. Strangelove" parodiert den Kalten Krieg schonungslos.' },
    { q:'Welche Komödie von Mel Brooks parodiert den Western?', a:["Young Frankenstein","Blazing Saddles","Spaceballs","The Producers"], c:1, d:2, f:'"Blazing Saddles" (1974) ist auch eine Rassismus-Satire.' },
    { q:'In welchem Film sagt Will Ferrell "I\'m kind of a big deal"?', a:["Elf","Step Brothers","Talladega Nights","Anchorman"], c:3, d:2, f:'Ron Burgundy in "Anchorman: The Legend of Ron Burgundy" (2004).' },
    { q:'Wer spielt den Detektiv Frank Drebin in der "Naked Gun"-Reihe?', a:["Bill Murray","Steve Martin","Leslie Nielsen","Chevy Chase"], c:2, d:2, f:'Leslie Nielsen wechselte von Dramen zur Komödie — mit riesigem Erfolg.' },
    { q:'In welchem Film sagt Dr. Rumack "Don\'t call me Shirley"?', a:["The Naked Gun","Airplane!","Police Academy","Hot Shots!"], c:1, d:2, f:'Leslie Nielsen als Dr. Rumack — klassische Deadpan-Komödie.' },
    { q:'Welche Komödie zeigt Charlie Chaplin als kleinen Vagabunden in der Industrie?', a:["The Kid","City Lights","Modern Times","The Great Dictator"], c:2, d:2, f:'"Modern Times" (1936) ist eine Satire auf die Massenproduktion.' },
    { q:'Was ist "Cringe Comedy"?', a:["Comedy über Arme","Komödie bei der man sich fremdschämt","Absurde Situationskomödie","Stand-Up Comedy"], c:1, d:2, f:'Genre durch "The Office" (UK) und "Curb Your Enthusiasm" geprägt.' },
    { q:'Welcher Film parodiert als "Mockumentary" den Heavy-Metal-Tourbus?', a:["This Is Spinal Tap","Best in Show","Waiting for Guffman","A Mighty Wind"], c:0, d:2, f:'"This Is Spinal Tap" (1984) von Rob Reiner — die Mutter aller Mockumentaries.' },
    { q:'Buster Keaton ist berühmt für Stunts in seinen Stummfilmen — welche Besonderheit hatte er?', a:["Er filmte immer in Schwarz-Weiß","Er lachte nie auf der Leinwand","Er schrieb alle Drehbücher selbst","Er nutzte keine Stunt-Doubles"], c:1, d:2, f:'"The Great Stone Face" — Keatons Markenzeichen war sein ausdrucksloses Gesicht.' },
    { q:'Wer drehte die Satire "American Movie" (1999)?', a:["Michael Moore","Chris Smith","Morgan Spurlock","Werner Herzog"], c:1, d:3, f:'"American Movie" begleitet einen scheiternden Horrorfilm-Regisseur — Dokumentarkomödie.' },
  ],

  musical: [
    { q:'Wer inszenierte "La La Land"?', a:["Damien Chazelle","Rob Marshall","Baz Luhrmann","Steven Spielberg"], c:0, d:1, f:'Chazelle kombinierte Jazz mit klassischem Hollywood-Feeling.' },
    { q:'In welchem Film singt Judy Garland "Over the Rainbow"?', a:["Meet Me in St. Louis","The Harvey Girls","The Wizard of Oz","Easter Parade"], c:2, d:1, f:'"The Wizard of Oz" (1939) ist eines der bekanntesten Musicals der Filmgeschichte.' },
    { q:'Welcher Broadway-Klassiker wurde mit Meryl Streep und ABBA-Songs verfilmt?', a:["Chicago","Grease","Mamma Mia!","Sweeney Todd"], c:2, d:1, f:'Mamma Mia! (2008) basiert auf ABBA-Songs.' },
    { q:'In "Grease" (1978) spielt John Travolta welche Figur?', a:["Danny Zuko","Sandy Olsson","Kenickie","Doody"], c:0, d:1, f:'Danny und Sandy gehören zu den ikonischsten Pärchen der Filmgeschichte.' },
    { q:'Welches Musical zeigt das Leben von Evita Perón mit Madonna?', a:["Chicago","Evita","Rent","Cabaret"], c:1, d:1, f:'Alan Parkers Verfilmung (1996) mit Madonna als Evita.' },
    { q:'Welches Musical spielt in Chicago und dreht sich um Mord und Ruhm?', a:["Chicago","Hamilton","Rent","Cabaret"], c:0, d:1, f:'"Chicago" gewann 2003 den Oscar für Besten Film.' },
    { q:'Welcher Film von Baz Luhrmann spielt im Paris des Jahres 1900?', a:["Romeo + Juliet","The Great Gatsby","Australia","Moulin Rouge!"], c:3, d:1, f:'"Moulin Rouge!" (2001) war für 8 Oscars nominiert.' },
    { q:'In "West Side Story" ist der Konflikt eine Adaption von...', a:["Julius Caesar","Romeo und Julia","Hamlet","Othello"], c:1, d:1, f:'Bernsteins Musical von 1957 verlegt Romeo und Julia nach New York.' },
    { q:'Welcher Schauspieler tanzte 1952 im Regen und machte "Singin\' in the Rain" unsterblich?', a:["Frank Sinatra","Fred Astaire","Gene Kelly","Donald O'Connor"], c:2, d:1, f:'Gene Kelly improvisierte den Regen-Tanz mit Fieber.' },
    { q:'In welchem Film verkörpert Hugh Jackman den Zirkuspionier P.T. Barnum?', a:["Logan","The Greatest Showman","Les Misérables","Kate & Leopold"], c:1, d:1, f:'"The Greatest Showman" (2017) mit spektakulären Songs.' },
    { q:'In welchem Film von Damien Chazelle wird Jazz und Hollywood-Träume verbunden?', a:["Whiplash","First Man","La La Land","Babylon"], c:2, d:1, f:'"La La Land" (2016) — Ryan Gosling und Emma Stone tanzen unter den Sternen.' },
    { q:'Was ist das berühmteste Lied aus dem Musical "The Sound of Music"?', a:["My Favorite Things","Do-Re-Mi","Edelweiss","The Hills Are Alive"], c:3, d:1, f:'"The Hills Are Alive" — das Eröffnungslied von Marias Lauf über die Alpen.' },
    { q:'Welcher Song ist aus "Singin\' in the Rain"?', a:["Good Morning","My Favorite Things","America","Memory"], c:0, d:2, f:'Good Morning ist ein Klassiker.' },
    { q:'In welchem Film singt Jennifer Hudson "And I Am Telling You"?', a:["Dreamgirls","Chicago","Precious","The Color Purple"], c:0, d:2, f:'Hudsons Debüt in "Dreamgirls" (2006) brachte ihr einen Oscar.' },
    { q:'Tim Burton verfilmte welches Sondheim-Musical mit Johnny Depp als Barbier?', a:["Into the Woods","Company","Sweeney Todd","Little Shop of Horrors"], c:2, d:2, f:'"Sweeney Todd" (2007) — der teuflische Barbier der Fleet Street.' },
    { q:'Welcher Schauspieler tanzte und choreografierte "An American in Paris" (1951)?', a:["Fred Astaire","Gene Kelly","Frank Sinatra","Donald O'Connor"], c:1, d:2, f:'Gene Kelly tanzte sich unsterblich in die Filmgeschichte.' },
    { q:'Welche Sängerin spielte die Hauptrolle im Musical "Funny Girl" (1968)?', a:["Liza Minnelli","Julie Andrews","Barbra Streisand","Judy Garland"], c:2, d:2, f:'Barbra Streisand gewann dafür den Oscar und wurde zum Megastar.' },
    { q:'Welcher Komponist schrieb die Musik für "West Side Story" (1957)?', a:["Cole Porter","George Gershwin","Leonard Bernstein","Jule Styne"], c:2, d:2, f:'Leonard Bernstein — in Zusammenarbeit mit Stephen Sondheim als Texter.' },
    { q:'In welchem Musical-Film spielt Judy Garland eine Frau, die nach Hollywood kommt?', a:["A Star Is Born","Easter Parade","The Harvey Girls","Meet Me in St. Louis"], c:0, d:2, f:'"A Star Is Born" (1954) — spätere Versionen mit Barbra Streisand (1976) und Lady Gaga (2018).' },
    { q:'Welches Hit-Musical verfilmte Lin-Manuel Miranda?', a:["In the Heights","Rent","Tick Tick Boom","Hamilton"], c:0, d:3, f:'In the Heights wurde adaptiert, Hamilton als Stage-Film veröffentlicht.' },
  ],

  scifi: [
    { q:'"Tears in rain" ist ein berühmtes Zitat aus...', a:["Terminator 2","Matrix","Blade Runner","Alien"], c:2, d:1, f:'Roy Battys Monolog wurde stark improvisiert.' },
    { q:'Welches Jahr ist der Titel von Kubricks Sci-Fi-Epos?', a:["1984","2001","2010","3000"], c:1, d:1, f:'2001: A Space Odyssey.' },
    { q:'Wer führte Regie bei "Arrival"?', a:["Ridley Scott","Denis Villeneuve","Christopher Nolan","James Cameron"], c:1, d:1, f:'Villeneuve schuf ein ruhiges Sci-Fi-Meisterwerk über Sprache.' },
    { q:'In welchem Film spielt Sigourney Weaver Ripley, Überlebende unter Außerirdischen?', a:["Predator","The Thing","Alien","Event Horizon"], c:2, d:1, f:'"Alien" (1979) von Ridley Scott — Horror im Weltall.' },
    { q:'Welcher Sci-Fi-Film von 1982 handelt von einem Detektiv auf der Suche nach Replikanten?', a:["Blade Runner","Robocop","Total Recall","A.I."], c:0, d:1, f:'"Blade Runner" von Ridley Scott gilt als Meilenstein des Genres.' },
    { q:'Wer drehte "Interstellar" (2014)?', a:["Ridley Scott","James Cameron","Christopher Nolan","Denis Villeneuve"], c:2, d:1, f:'Nolans Weltraum-Epos über Gravitation und Liebe.' },
    { q:'In "Star Wars: Episode IV" — wie heißt die Raumstation des Imperiums?', a:["Enterprise","Millenium Falcon","Death Star","Deathstar Prime"], c:2, d:1, f:'"Das ist kein Mond..."' },
    { q:'In welchem Spielberg-Film landet ein freundlicher Außerirdischer auf der Erde?', a:["Close Encounters","E.T. der Außerirdische","Signs","Contact"], c:1, d:1, f:'"E.T." (1982) ist eines der erfolgreichsten Filme aller Zeiten.' },
    { q:'Welcher Villeneuve-Film basiert auf dem Roman von Frank Herbert?', a:["Arrival","Blade Runner 2049","Dune","Prisoners"], c:2, d:1, f:'"Dune" (2021) wurde ein weltweiter Kassenerfolg.' },
    { q:'In welchem Film muss ein Astronaut auf dem Mars alleine überleben?', a:["Gravity","Interstellar","The Martian","Ad Astra"], c:2, d:1, f:'"The Martian" (2015) mit Matt Damon — basierend auf Andy Weirs Roman.' },
    { q:'Welcher Cameron-Film ist bis heute einer der teuersten Science-Fiction-Filme?', a:["Terminator 2","True Lies","Avatar","The Abyss"], c:2, d:1, f:'"Avatar" (2009) hält bis heute Kassenrekorde.' },
    { q:'In welchem Film lebt die Menschheit in einer simulierten Realität?', a:["Total Recall","Dark City","The Matrix","eXistenZ"], c:2, d:1, f:'Die Wachowskis drehten "The Matrix" 1999.' },
    { q:'Was steuert das Raumschiff "Discovery One" in "2001: A Space Odyssey"?', a:["Ein Pilot","HAL 9000","Ein Autopilot","Das Missionskontrollzentrum"], c:1, d:1, f:'"I\'m sorry Dave, I\'m afraid I can\'t do that." — HAL 9000.' },
    { q:'Was ist HAL 9000?', a:["Ein Raumschiff","Ein außerirdisches Wesen","Ein Bordcomputer","Ein Astronaut"], c:2, d:1, f:'HAL 9000 ist der KI-Bordcomputer in "2001: A Space Odyssey".' },
    { q:'In welchem Film von Ridley Scott erscheint das "Xenomorph" zum ersten Mal?', a:["Prometheus","Alien","Aliens","Alien 3"], c:1, d:1, f:'"Alien" (1979) — Design von H.R. Giger, der dafür den Oscar gewann.' },
    { q:'"Solaris" (1972) ist ein Werk von welchem Regisseur?', a:["Stanley Kubrick","Andrei Tarkovsky","Ingmar Bergman","Federico Fellini"], c:1, d:2, f:'Tarkovskys philosophischer Sci-Fi-Film über Bewusstsein.' },
    { q:'Welcher Film zeigt eine KI, die versucht ihren Schöpfer zu manipulieren?', a:["Her","Transcendence","Ex Machina","I, Robot"], c:2, d:2, f:'"Ex Machina" (2014) fragt: Kann eine KI echte Gefühle haben?' },
    { q:'Welcher Film von James Cameron verdiente als erster über 2 Milliarden Dollar?', a:["Aliens","True Lies","Titanic","The Abyss"], c:2, d:2, f:'"Titanic" (1997) — damals der erfolgreichste Film aller Zeiten.' },
    { q:'In welchem Sci-Fi-Film kämpft der Mensch gegen Maschinen im Jahr 2029?', a:["RoboCop","The Terminator","Elysium","Edge of Tomorrow"], c:1, d:2, f:'"The Terminator" (1984) — James Camerons Durchbruch als Regisseur.' },
    { q:'Welcher Sci-Fi-Klassiker von 1956 handelt von einer Invasion durch Pflanzen?', a:["The Thing From Another World","Invasion of the Body Snatchers","The Day the Earth Stood Still","It Came from Outer Space"], c:1, d:3, f:'"Invasion of the Body Snatchers" — eine Parabel auf McCarthyismus und Konformismus.' },
  ],

  nineties: [
    { q:'"Pulp Fiction" stammt aus dem Jahr?', a:["1992","1994","1995","1996"], c:1, d:1, f:'1994 war eines der besten Kinojahre.' },
    { q:'Die erste Regel des Fight Clubs lautet?', a:["Gewinnen","Wir reden nicht über den Fight Club","Keine Hemden","Nur zwei pro Kampf"], c:1, d:1, f:'Du verlierst kein Wort darüber.' },
    { q:'"Matrix" (1999) hat welche dominierende Farbpalette?', a:["Rot/Blau","Grau","Grün","Neonpink"], c:2, d:1, f:'Die "Matrix"-Szenen sind stark grün getönt.' },
    { q:'Welcher Schauspieler spielte Forrest Gump?', a:["Tom Hanks","Tom Cruise","Kevin Costner","Mel Gibson"], c:0, d:1, f:'Tom Hanks gewann 1994 seinen zweiten Oscar in Folge.' },
    { q:'Welcher Kultfilm von 1996 handelt von Drogensucht im schottischen Edinburgh?', a:["Snatch","Lock Stock","Trainspotting","Shallow Grave"], c:2, d:1, f:'Danny Boyles "Trainspotting" mit Ewan McGregor.' },
    { q:'Welcher Disney-Film erschien 1994 mit Musik von Elton John?', a:["Aladdin","Beauty and the Beast","The Lion King","Pocahontas"], c:2, d:1, f:'"Der König der Löwen" mit Musik von Elton John und Hans Zimmer.' },
    { q:'Wer spielt in "Good Will Hunting" (1997) den Therapeuten?', a:["Jeff Bridges","Gene Hackman","Robin Williams","Dustin Hoffman"], c:2, d:1, f:'Robin Williams gewann für diese Rolle den Oscar.' },
    { q:'"The Sixth Sense" (1999) — was sieht der kleine Cole Sear?', a:["Geister","Engel","Teufel","Die Zukunft"], c:0, d:1, f:'"I see dead people" ist eines der bekanntesten Filmzitate.' },
    { q:'In welchem Film tanzen John Travolta und Uma Thurman in einem Restaurant?', a:["Get Shorty","Pulp Fiction","Jackie Brown","Reservoir Dogs"], c:1, d:1, f:'Das Twist-Wettbewerb in Jack Rabbit Slim\'s ist ikonisch.' },
    { q:'Welcher Film startete die "Buddy-Cop"-Ära mit Will Smith und Martin Lawrence?', a:["Enemy of the State","Ali","Bad Boys","Men in Black"], c:2, d:1, f:'"Bad Boys" (1995) war Michael Bays Regiedebüt.' },
    { q:'Welche Hauptfigur in "The Big Lebowski" (1998) wird "The Dude" genannt?', a:["Walter Sobchak","Maude Lebowski","Jeffrey Lebowski","Donny Kerabatsos"], c:2, d:1, f:'Jeff Bridges als "The Dude" — Kultfigur der Filmgeschichte.' },
    { q:'Welcher Film zeigte Kevin McAllister allein zu Haus (in New York)?', a:["Home Alone 2","Home Alone","A Christmas Story","National Lampoon's Christmas Vacation"], c:0, d:1, f:'"Kevin allein in New York" (1992).' },
    { q:'"In welchem Jahr veröffentlichte Spielberg seinen Holocaust-Film "Schindlers Liste"?', a:["1991","1993","1995","1997"], c:1, d:1, f:'"Schindlers Liste" (1993) gewann 7 Oscars, darunter Bester Film.' },
    { q:'Welcher Film von 1994 zeigte eine Dinosaurier-Attraktion außer Kontrolle?', a:["Jurassic Park","The Lost World","Congo","Species"], c:0, d:1, f:'"Jurassic Park" von Steven Spielberg — revolutionierte CGI-Effekte.' },
    { q:'Welcher Film von Quentin Tarantino erschien 1992 als Regiedebüt?', a:["Jackie Brown","From Dusk till Dawn","Reservoir Dogs","True Romance"], c:2, d:1, f:'"Reservoir Dogs" — gedreht für 1,2 Millionen Dollar, ein Meisterwerk.' },
    { q:'Welcher Film von 1999 nutzte Found-Footage-Stil und erschreckte das Publikum?', a:["Scream","The Blair Witch Project","I Know What You Did Last Summer","Urban Legend"], c:1, d:2, f:'The Blair Witch Project startete das Found-Footage-Genre.' },
    { q:'Wer spielte in "Léon: The Professional" (1994) die junge Mathilda?', a:["Drew Barrymore","Natalie Portman","Kirsten Dunst","Winona Ryder"], c:1, d:2, f:'Natalie Portmans Filmdebüt im Alter von 13 Jahren.' },
    { q:'Wer schrieb und spielte in "Good Will Hunting" (1997) die Hauptrolle?', a:["Kevin Smith","Ben Affleck & Matt Damon","Ethan Hawke & Ben Stiller","Owen Wilson & Wes Anderson"], c:1, d:2, f:'Matt Damon und Ben Affleck gewannen den Oscar für das Originaldrehbuch.' },
    { q:'Welcher Kultfilm von 1999 handelt von einer Bürorevolution gegen ein Drucker-Unternehmen?', a:["The Matrix","Fight Club","American Beauty","Office Space"], c:3, d:2, f:'"Office Space" von Mike Judge — heute Kultfilm über Bürohölle.' },
    { q:'In welchem Coen-Brüder-Film erscheint die legendäre Holzhacker-Szene?', a:["The Big Lebowski","Barton Fink","Fargo","Blood Simple"], c:2, d:2, f:'"Fargo" (1996) — Frances McDormand gewann den Oscar für die Polizistin Marge Gunderson.' },
  ],

  worldcinema: [
    { q:'"Die fabelhafte Welt der Amélie" spielt in...', a:["London","Paris","Marseille","Lyon"], c:1, d:1, f:'Ein romantisiertes Montmartre in Paris.' },
    { q:'"Stadt der Gottes" (City of God) wurde in welchem Land gedreht?', a:["Spanien","Kolumbien","Mexiko","Brasilien"], c:3, d:1, f:'Brasilien, in den Favelas von Rio.' },
    { q:'Wer führte Regie beim mexikanischen Film "Roma"?', a:["Guillermo del Toro","Alfonso Cuarón","Alejandro G. Iñárritu","Carlos Reygadas"], c:1, d:1, f:'Cuarón gewann den Oscar für beste Regie.' },
    { q:'Welcher französische Film handelt von einem Querschnittsgelähmten und seinem Pfleger?', a:["Intouchables","Les Misérables","Blue Is the Warmest Color","La Haine"], c:0, d:1, f:'"Ziemlich beste Freunde" (Intouchables, 2011) war ein weltweiter Megaerfolg.' },
    { q:'In welchem Land entstand das Kino-Phänomen "Bollywood"?', a:["Pakistan","Bangladesch","Indien","Sri Lanka"], c:2, d:1, f:'Mumbai (früher Bombay) ist das Zentrum der indischen Filmindustrie.' },
    { q:'In welchem Land spielt das oscarprämierte Drama "A Separation" (2011)?', a:["Türkei","Ägypten","Iran","Afghanistan"], c:2, d:2, f:'Asghar Farhadis Film war der erste iranische Oscar-Gewinner.' },
    { q:'Welcher dänische Regisseur ist bekannt für "Melancholia" und "Breaking the Waves"?', a:["Susanne Bier","Thomas Vinterberg","Lars von Trier","Bille August"], c:2, d:2, f:'Lars von Trier ist für seinen provokativen Stil bekannt.' },
    { q:'Welcher koreanische Film von Park Chan-wook gewann den Grand Prix in Cannes?', a:["The Handmaiden","Sympathy for Mr. Vengeance","Oldboy","Stoker"], c:2, d:2, f:'"Oldboy" (2003) ist Teil der Rache-Trilogie.' },
    { q:'Welcher japanische Film über Samurai von 1954 gilt als Meisterwerk?', a:["Ran","Rashomon","Die sieben Samurai","Yojimbo"], c:2, d:2, f:'Kurosawas "Die sieben Samurai" beeinflusste unzählige Filmemacher.' },
    { q:'Welches ist das bekannteste Werk des italienischen Regisseurs Federico Fellini?', a:["8½","Roma","Amarcord","La Dolce Vita"], c:3, d:2, f:'"La Dolce Vita" (1960) prägte den Begriff als Lebenseinstellung.' },
    { q:'In welchem Land wurde "Pan\'s Labyrinth" von Guillermo del Toro gedreht?', a:["Mexiko","Spanien","Argentinien","Chile"], c:1, d:2, f:'"Pan\'s Labyrinth" (2006) spielt im Spanien nach dem Bürgerkrieg.' },
    { q:'Welcher chinesisch-amerikanische Regisseur drehte "Crouching Tiger, Hidden Dragon"?', a:["Zhang Yimou","John Woo","Ang Lee","Wong Kar-wai"], c:2, d:2, f:'Ang Lee gewann für diesen Film den Oscar für Besten fremdsprachigen Film.' },
    { q:'Welcher iranische Regisseur drehte "The Salesman" (2016) und boykottierte die Oscars?', a:["Abbas Kiarostami","Jafar Panahi","Asghar Farhadi","Mohsen Makhmalbaf"], c:2, d:2, f:'Farhadi gewann 2017 den Oscar — und ließ ihn durch andere entgegennehmen.' },
    { q:'Welcher südkoreanische Regisseur drehte "Memories of Murder" und später "Parasite"?', a:["Park Chan-wook","Lee Chang-dong","Kim Jee-woon","Bong Joon-ho"], c:3, d:2, f:'Bong Joon-ho ist einer der wichtigsten Filmemacher des 21. Jahrhunderts.' },
    { q:'Welcher mexikanische Regisseur gewann dreimal den Oscar für Beste Regie?', a:["Guillermo del Toro","Alfonso Cuarón","Alejandro G. Iñárritu","Carlos Reygadas"], c:1, d:2, f:'Cuarón: Roma (2018), Gravity (2013) — insgesamt 2 Oscars für Regie.' },
    { q:'Welcher rumänische Film über eine illegale Abtreibung gewann 2007 die Goldene Palme?', a:["The Death of Mr. Lazarescu","California Dreamin","4 Months 3 Weeks 2 Days","Police Adjective"], c:2, d:2, f:'Cristian Mungius Film erschütterte Cannes und die Welt.' },
    { q:'Welcher chinesische Film gewann 2000 den Oscar für "Besten Fremdsprachigen Film"?', a:["Hero","Raise the Red Lantern","Crouching Tiger Hidden Dragon","Farewell My Concubine"], c:2, d:2, f:'"Crouching Tiger, Hidden Dragon" von Ang Lee — 4 Oscars insgesamt.' },
    { q:'Wer ist der bekannteste Regisseur des "Hongkong Action-Kinos"?', a:["Bruce Lee","Jackie Chan","John Woo","Sammo Hung"], c:2, d:2, f:'John Woo prägte das Heroic Bloodshed Genre mit Filmen wie "Hard Boiled" und "The Killer".' },
    { q:'Welcher polnische Regisseur ist bekannt für "Das doppelte Leben der Veronika"?', a:["Andrzej Wajda","Roman Polanski","Krzysztof Kieślowski","Agnieszka Holland"], c:2, d:3, f:'Kieślowski drehte auch die Trilogie "Bleu, Blanc, Rouge".' },
    { q:'Welcher türkische Regisseur ist bekannt für "Uzak" (2002) und "Winter Sleep"?', a:["Fatih Akin","Nuri Bilge Ceylan","Zeki Demirkubuz","Reha Erdem"], c:1, d:3, f:'Ceylan gewann 2014 die Goldene Palme für "Winter Sleep".' },
  ],

};
