// New York Times: The 100 Best Movies of the 21st Century (2025), in Rangfolge.
// Quelle: IMDb-Liste ls599610113, Titel/Jahr über TMDB, Links über Letterboxd, 29.09.26.
// Stimmungen sind redaktionelle Vorschläge und in der App änderbar.
export const STARTER_NAME='New York Times: Die 100 besten Filme des 21. Jahrhunderts';
export const starterFilms=[
 ["https://letterboxd.com/film/parasite-2019/", "Parasite", "2019", ["dark", "deep"]],
 ["https://letterboxd.com/film/mulholland-drive/", "Mulholland Drive", "2001", ["dark"]],
 ["https://letterboxd.com/film/there-will-be-blood/", "There Will Be Blood", "2007", ["deep", "dark"]],
 ["https://letterboxd.com/film/in-the-mood-for-love/", "In the Mood for Love", "2000", ["deep"]],
 ["https://letterboxd.com/film/moonlight-2016/", "Moonlight", "2016", ["deep"]],
 ["https://letterboxd.com/film/no-country-for-old-men/", "No Country for Old Men", "2007", ["dark"]],
 ["https://letterboxd.com/film/eternal-sunshine-of-the-spotless-mind/", "Eternal Sunshine of the Spotless Mind", "2004", ["deep", "warm"]],
 ["https://letterboxd.com/film/get-out-2017/", "Get Out", "2017", ["dark"]],
 ["https://letterboxd.com/film/spirited-away/", "Spirited Away", "2001", ["warm"]],
 ["https://letterboxd.com/film/the-social-network/", "The Social Network", "2010", ["deep"]],
 ["https://letterboxd.com/film/mad-max-fury-road/", "Mad Max: Fury Road", "2015", ["energy"]],
 ["https://letterboxd.com/film/the-zone-of-interest/", "The Zone of Interest", "2023", ["dark", "deep"]],
 ["https://letterboxd.com/film/children-of-men/", "Children of Men", "2006", ["energy", "dark"]],
 ["https://letterboxd.com/film/inglourious-basterds/", "Inglourious Basterds", "2009", ["energy", "dark"]],
 ["https://letterboxd.com/film/city-of-god/", "City of God", "2002", ["energy", "dark"]],
 ["https://letterboxd.com/film/crouching-tiger-hidden-dragon/", "Crouching Tiger, Hidden Dragon", "2000", ["energy"]],
 ["https://letterboxd.com/film/brokeback-mountain/", "Brokeback Mountain", "2005", ["deep"]],
 ["https://letterboxd.com/film/y-tu-mama-tambien/", "Y Tu Mamá También", "2001", ["deep", "warm"]],
 ["https://letterboxd.com/film/zodiac/", "Zodiac", "2007", ["dark"]],
 ["https://letterboxd.com/film/the-wolf-of-wall-street/", "The Wolf of Wall Street", "2013", ["energy"]],
 ["https://letterboxd.com/film/the-royal-tenenbaums/", "The Royal Tenenbaums", "2001", ["warm"]],
 ["https://letterboxd.com/film/the-grand-budapest-hotel/", "The Grand Budapest Hotel", "2014", ["warm"]],
 ["https://letterboxd.com/film/boyhood/", "Boyhood", "2014", ["deep", "warm"]],
 ["https://letterboxd.com/film/her/", "Her", "2013", ["deep"]],
 ["https://letterboxd.com/film/phantom-thread/", "Phantom Thread", "2017", ["deep", "dark"]],
 ["https://letterboxd.com/film/anatomy-of-a-fall/", "Anatomy of a Fall", "2023", ["dark", "deep"]],
 ["https://letterboxd.com/film/adaptation/", "Adaptation.", "2002", ["warm"]],
 ["https://letterboxd.com/film/the-dark-knight/", "The Dark Knight", "2008", ["energy", "dark"]],
 ["https://letterboxd.com/film/arrival-2016/", "Arrival", "2016", ["deep"]],
 ["https://letterboxd.com/film/lost-in-translation/", "Lost in Translation", "2003", ["deep", "warm"]],
 ["https://letterboxd.com/film/the-departed/", "The Departed", "2006", ["dark", "energy"]],
 ["https://letterboxd.com/film/bridesmaids/", "Bridesmaids", "2011", ["warm"]],
 ["https://letterboxd.com/film/a-separation/", "A Separation", "2011", ["deep"]],
 ["https://letterboxd.com/film/walle/", "WALL·E", "2008", ["warm"]],
 ["https://letterboxd.com/film/a-prophet/", "A Prophet", "2009", ["dark"]],
 ["https://letterboxd.com/film/a-serious-man/", "A Serious Man", "2009", ["deep"]],
 ["https://letterboxd.com/film/call-me-by-your-name/", "Call Me by Your Name", "2017", ["deep", "warm"]],
 ["https://letterboxd.com/film/portrait-of-a-lady-on-fire/", "Portrait of a Lady on Fire", "2019", ["deep"]],
 ["https://letterboxd.com/film/lady-bird/", "Lady Bird", "2017", ["warm"]],
 ["https://letterboxd.com/film/yi-yi/", "Yi Yi", "2000", ["deep"]],
 ["https://letterboxd.com/film/amelie/", "Amélie", "2001", ["warm"]],
 ["https://letterboxd.com/film/the-master-2012/", "The Master", "2012", ["deep"]],
 ["https://letterboxd.com/film/oldboy/", "Oldboy", "2003", ["dark", "energy"]],
 ["https://letterboxd.com/film/once-upon-a-time-in-hollywood/", "Once Upon a Time... in Hollywood", "2019", ["warm", "energy"]],
 ["https://letterboxd.com/film/moneyball/", "Moneyball", "2011", ["warm"]],
 ["https://letterboxd.com/film/roma-2018/", "Roma", "2018", ["deep"]],
 ["https://letterboxd.com/film/almost-famous/", "Almost Famous", "2000", ["warm"]],
 ["https://letterboxd.com/film/the-lives-of-others/", "The Lives of Others", "2006", ["dark", "deep"]],
 ["https://letterboxd.com/film/before-sunset/", "Before Sunset", "2004", ["warm", "deep"]],
 ["https://letterboxd.com/film/up/", "Up", "2009", ["warm"]],
 ["https://letterboxd.com/film/12-years-a-slave/", "12 Years a Slave", "2013", ["deep"]],
 ["https://letterboxd.com/film/the-favourite/", "The Favourite", "2018", ["deep"]],
 ["https://letterboxd.com/film/borat-cultural-learnings-of-america-for-make-benefit-glorious-nation-of-kazakhstan/", "Borat: Cultural Learnings of America for Make Benefit Glorious Nation of Kazakhstan", "2006", ["warm"]],
 ["https://letterboxd.com/film/pans-labyrinth/", "Pan's Labyrinth", "2006", ["dark"]],
 ["https://letterboxd.com/film/inception/", "Inception", "2010", ["energy"]],
 ["https://letterboxd.com/film/punch-drunk-love/", "Punch-Drunk Love", "2002", ["warm"]],
 ["https://letterboxd.com/film/best-in-show/", "Best in Show", "2000", ["warm"]],
 ["https://letterboxd.com/film/uncut-gems/", "Uncut Gems", "2019", ["energy", "dark"]],
 ["https://letterboxd.com/film/toni-erdmann/", "Toni Erdmann", "2016", ["warm", "deep"]],
 ["https://letterboxd.com/film/whiplash-2014/", "Whiplash", "2014", ["energy"]],
 ["https://letterboxd.com/film/kill-bill-vol-1/", "Kill Bill: Vol. 1", "2003", ["energy"]],
 ["https://letterboxd.com/film/memento/", "Memento", "2000", ["dark"]],
 ["https://letterboxd.com/film/little-miss-sunshine/", "Little Miss Sunshine", "2006", ["warm"]],
 ["https://letterboxd.com/film/gone-girl/", "Gone Girl", "2014", ["dark"]],
 ["https://letterboxd.com/film/oppenheimer-2023/", "Oppenheimer", "2023", ["deep"]],
 ["https://letterboxd.com/film/spotlight/", "Spotlight", "2015", ["deep"]],
 ["https://letterboxd.com/film/tar-2022/", "TÁR", "2022", ["deep"]],
 ["https://letterboxd.com/film/the-hurt-locker/", "The Hurt Locker", "2008", ["energy", "dark"]],
 ["https://letterboxd.com/film/under-the-skin-2013/", "Under the Skin", "2014", ["dark"]],
 ["https://letterboxd.com/film/let-the-right-one-in/", "Let the Right One In", "2008", ["dark"]],
 ["https://letterboxd.com/film/oceans-eleven-2001/", "Ocean's Eleven", "2001", ["energy", "warm"]],
 ["https://letterboxd.com/film/carol-2015/", "Carol", "2015", ["deep"]],
 ["https://letterboxd.com/film/ratatouille/", "Ratatouille", "2007", ["warm"]],
 ["https://letterboxd.com/film/the-florida-project/", "The Florida Project", "2017", ["warm", "deep"]],
 ["https://letterboxd.com/film/amour/", "Amour", "2012", ["deep"]],
 ["https://letterboxd.com/film/o-brother-where-art-thou/", "O Brother, Where Art Thou?", "2000", ["warm"]],
 ["https://letterboxd.com/film/everything-everywhere-all-at-once/", "Everything Everywhere All at Once", "2022", ["energy", "warm"]],
 ["https://letterboxd.com/film/aftersun/", "Aftersun", "2022", ["deep"]],
 ["https://letterboxd.com/film/the-tree-of-life-2011/", "The Tree of Life", "2011", ["deep"]],
 ["https://letterboxd.com/film/volver/", "Volver", "2006", ["warm", "deep"]],
 ["https://letterboxd.com/film/black-swan/", "Black Swan", "2010", ["dark"]],
 ["https://letterboxd.com/film/the-act-of-killing/", "The Act of Killing", "2012", ["dark"]],
 ["https://letterboxd.com/film/inside-llewyn-davis/", "Inside Llewyn Davis", "2013", ["deep"]],
 ["https://letterboxd.com/film/melancholia/", "Melancholia", "2011", ["deep"]],
 ["https://letterboxd.com/film/anchorman-the-legend-of-ron-burgundy/", "Anchorman: The Legend of Ron Burgundy", "2004", ["warm"]],
 ["https://letterboxd.com/film/past-lives/", "Past Lives", "2023", ["deep", "warm"]],
 ["https://letterboxd.com/film/the-lord-of-the-rings-the-fellowship-of-the-ring/", "The Lord of the Rings: The Fellowship of the Ring", "2001", ["energy"]],
 ["https://letterboxd.com/film/the-gleaners-and-i/", "The Gleaners and I", "2000", ["warm"]],
 ["https://letterboxd.com/film/interstellar/", "Interstellar", "2014", ["deep", "energy"]],
 ["https://letterboxd.com/film/frances-ha/", "Frances Ha", "2013", ["warm"]],
 ["https://letterboxd.com/film/fish-tank/", "Fish Tank", "2009", ["deep"]],
 ["https://letterboxd.com/film/gladiator-2000/", "Gladiator", "2000", ["energy"]],
 ["https://letterboxd.com/film/michael-clayton/", "Michael Clayton", "2007", ["dark"]],
 ["https://letterboxd.com/film/minority-report/", "Minority Report", "2002", ["energy", "dark"]],
 ["https://letterboxd.com/film/the-worst-person-in-the-world/", "The Worst Person in the World", "2021", ["warm", "deep"]],
 ["https://letterboxd.com/film/black-panther/", "Black Panther", "2018", ["energy"]],
 ["https://letterboxd.com/film/gravity-2013/", "Gravity", "2013", ["energy"]],
 ["https://letterboxd.com/film/grizzly-man/", "Grizzly Man", "2005", ["deep"]],
 ["https://letterboxd.com/film/memories-of-murder/", "Memories of Murder", "2003", ["dark"]],
 ["https://letterboxd.com/film/superbad/", "Superbad", "2007", ["warm"]]
];
